!  This file was generated by kMOS (kMC modelling on steroids)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2013.
!  The model was written by Juan M. Lorenzi.

!  This file is part of kmos.
!
!  kmos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
module proclist_pars
use kind_values
use base, only: &
    rates
use proclist_constants
use lattice, only: &
    pdo, &
    pdo_bridge, &
    pdo_hollow, &
    get_species

implicit none

! User parameters
integer(kind=iint), public :: A = 1
integer(kind=iint), public :: E_CO_bridge = 2
integer(kind=iint), public :: E_CO_diff_bridge_bridge = 3
integer(kind=iint), public :: E_CO_diff_bridge_hollow = 4
integer(kind=iint), public :: E_CO_diff_hollow_bridge = 5
integer(kind=iint), public :: E_CO_diff_hollow_hollow = 6
integer(kind=iint), public :: E_CO_hollow = 7
integer(kind=iint), public :: E_O2_ads_bridge_bridge = 8
integer(kind=iint), public :: E_O2_ads_bridge_hollow = 9
integer(kind=iint), public :: E_O2_ads_hollow_bridge = 10
integer(kind=iint), public :: E_O2_ads_hollow_hollow = 11
integer(kind=iint), public :: E_O_bridge = 12
integer(kind=iint), public :: E_O_diff_bridge_bridge = 13
integer(kind=iint), public :: E_O_diff_bridge_hollow = 14
integer(kind=iint), public :: E_O_diff_hollow_bridge = 15
integer(kind=iint), public :: E_O_diff_hollow_hollow = 16
integer(kind=iint), public :: E_O_hollow = 17
integer(kind=iint), public :: E_react_O_CO_bridge_bridge = 18
integer(kind=iint), public :: E_react_O_CO_bridge_hollow = 19
integer(kind=iint), public :: E_react_O_CO_hollow_bridge = 20
integer(kind=iint), public :: E_react_O_CO_hollow_hollow = 21
integer(kind=iint), public :: T = 22
integer(kind=iint), public :: V_CO_CO_bridge_bridge = 23
integer(kind=iint), public :: V_CO_CO_bridge_hollow = 24
integer(kind=iint), public :: V_CO_CO_hollow_bridge = 25
integer(kind=iint), public :: V_CO_CO_hollow_hollow = 26
integer(kind=iint), public :: V_CO_O_bridge_bridge = 27
integer(kind=iint), public :: V_CO_O_bridge_hollow = 28
integer(kind=iint), public :: V_CO_O_hollow_bridge = 29
integer(kind=iint), public :: V_CO_O_hollow_hollow = 30
integer(kind=iint), public :: V_O_CO_bridge_bridge = 31
integer(kind=iint), public :: V_O_CO_bridge_hollow = 32
integer(kind=iint), public :: V_O_CO_hollow_bridge = 33
integer(kind=iint), public :: V_O_CO_hollow_hollow = 34
integer(kind=iint), public :: V_O_O_bridge_bridge = 35
integer(kind=iint), public :: V_O_O_bridge_hollow = 36
integer(kind=iint), public :: V_O_O_hollow_bridge = 37
integer(kind=iint), public :: V_O_O_hollow_hollow = 38
integer(kind=iint), public :: p_COgas = 39
integer(kind=iint), public :: p_O2gas = 40
real(kind=rdouble), public, dimension(40) :: userpar

! Constants
real(kind=rdouble), parameter :: bar = 1.0000000000e+05
real(kind=rdouble), parameter :: eV = 1.6021765650e-19
real(kind=rdouble), parameter :: h = 6.6260695700e-34
real(kind=rdouble), parameter :: kboltzmann = 1.3806488000e-23
real(kind=rdouble), parameter :: pi = 3.1415926536e+00
real(kind=rdouble), parameter :: umass = 1.6605389210e-27

! Species masses
real(kind=rdouble), parameter :: m_CO = 2.8010400000e+01
real(kind=rdouble), parameter :: m_O2 = 3.1998800000e+01

! Species chemical potentials
integer(kind=iint), public :: mu_COgas = 1
integer(kind=iint), public :: mu_O2gas = 2
real(kind=rdouble), public, dimension(2) :: chempots
character(len=0), parameter, public :: byst_CO_ads_bridge = ""
character(len=0), parameter, public :: byst_CO_ads_hollow = ""
character(len=49), parameter, public :: byst_CO_des_bridge = "nr_CO_bridge &
    &nr_O_bridge &
    &nr_CO_hollow &
    &nr_O_hollow"
character(len=49), parameter, public :: byst_CO_des_hollow = "nr_CO_bridge &
    &nr_O_bridge &
    &nr_CO_hollow &
    &nr_O_hollow"
character(len=107), parameter, public :: byst_CO_diff_bridge_bridge_l = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_CO_diff_bridge_bridge_r = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_CO_diff_bridge_hollow = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_CO_diff_bridge_hollow_l = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_CO_diff_hollow_bridge = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_CO_diff_hollow_bridge_r = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_CO_diff_hollow_hollow_l = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_CO_diff_hollow_hollow_r = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=0), parameter, public :: byst_CO_oxi_bridge_bridge_l = ""
character(len=0), parameter, public :: byst_CO_oxi_bridge_bridge_r = ""
character(len=0), parameter, public :: byst_CO_oxi_bridge_hollow = ""
character(len=0), parameter, public :: byst_CO_oxi_bridge_hollow_l = ""
character(len=0), parameter, public :: byst_CO_oxi_hollow_bridge = ""
character(len=0), parameter, public :: byst_CO_oxi_hollow_bridge_r = ""
character(len=0), parameter, public :: byst_CO_oxi_hollow_hollow_l = ""
character(len=0), parameter, public :: byst_CO_oxi_hollow_hollow_r = ""
character(len=0), parameter, public :: byst_O2_ads_bridge_bridge = ""
character(len=0), parameter, public :: byst_O2_ads_bridge_hollow = ""
character(len=0), parameter, public :: byst_O2_ads_hollow_bridge = ""
character(len=0), parameter, public :: byst_O2_ads_hollow_hollow = ""
character(len=107), parameter, public :: byst_O2_des_bridge_bridge_r = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_O2_des_bridge_hollow = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_O2_des_hollow_bridge_r = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_O2_des_hollow_hollow_r = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_O_diff_bridge_bridge_l = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_O_diff_bridge_bridge_r = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_O_diff_bridge_hollow = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_O_diff_bridge_hollow_l = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_O_diff_hollow_bridge = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_O_diff_hollow_bridge_r = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_O_diff_hollow_hollow_l = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"
character(len=107), parameter, public :: byst_O_diff_hollow_hollow_r = "nr_CO_bridge1 &
    &nr_O_bridge1 &
    &nr_CO_bridge2 &
    &nr_O_bridge2 &
    &nr_CO_hollow1 &
    &nr_O_hollow1 &
    &nr_CO_hollow2 &
    &nr_O_hollow2"

contains
subroutine update_user_parameter(param,val)
    integer(kind=iint), intent(in) :: param
    real(kind=rdouble), intent(in) :: val
    userpar(param) = val
end subroutine update_user_parameter

subroutine get_user_parameter(param,val)
    integer(kind=iint), intent(in) :: param
    real(kind=rdouble), intent(out) :: val
    val = userpar(param)
end subroutine get_user_parameter

subroutine update_chempot(index,val)
    integer(kind=iint), intent(in) :: index
    real(kind=rdouble), intent(in) :: val
    chempots(index) = val
end subroutine update_chempot


function gr_CO_ads_bridge(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_CO_ads_bridge


    gr_CO_ads_bridge = rate_CO_ads_bridge()
    return

end function gr_CO_ads_bridge

function rate_CO_ads_bridge()


    real(kind=rdouble) :: rate_CO_ads_bridge
    rate_CO_ads_bridge = rates(CO_ads_bridge)
    return

end function rate_CO_ads_bridge


function gr_CO_ads_hollow(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_CO_ads_hollow


    gr_CO_ads_hollow = rate_CO_ads_hollow()
    return

end function gr_CO_ads_hollow

function rate_CO_ads_hollow()


    real(kind=rdouble) :: rate_CO_ads_hollow
    rate_CO_ads_hollow = rates(CO_ads_hollow)
    return

end function rate_CO_ads_hollow


function gr_CO_des_bridge(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(4) :: nr_vars
    real(kind=rdouble) :: gr_CO_des_bridge

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select

    gr_CO_des_bridge = rate_CO_des_bridge(nr_vars)
    return

end function gr_CO_des_bridge

function rate_CO_des_bridge(nr_vars)

    integer(kind=iint), dimension(4), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_CO_des_bridge
    rate_CO_des_bridge = rates (CO_des_bridge ) * exp ((1 / (&
    &kboltzmann  * userpar(T) ) ) * 2 * (nr_vars(1) * &
    &userpar(V_CO_CO_bridge_bridge)  + nr_vars(2) * &
    &userpar(V_CO_O_bridge_bridge)  + nr_vars(3) * &
    &userpar(V_CO_CO_bridge_hollow)  + nr_vars(4) * &
    &userpar(V_CO_O_bridge_hollow)  ) * eV )  

    return

end function rate_CO_des_bridge


function gr_CO_des_hollow(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(4) :: nr_vars
    real(kind=rdouble) :: gr_CO_des_hollow

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/0, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_CO_des_hollow = rate_CO_des_hollow(nr_vars)
    return

end function gr_CO_des_hollow

function rate_CO_des_hollow(nr_vars)

    integer(kind=iint), dimension(4), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_CO_des_hollow
    rate_CO_des_hollow = rates (CO_des_hollow ) * exp ((1 / (&
    &kboltzmann  * userpar(T) ) ) * 2 * (nr_vars(1) * &
    &userpar(V_CO_CO_hollow_bridge)  + nr_vars(2) * &
    &userpar(V_CO_O_hollow_bridge)  + nr_vars(3) * &
    &userpar(V_CO_CO_hollow_hollow)  + nr_vars(4) * &
    &userpar(V_CO_O_hollow_hollow)  ) * eV )  

    return

end function rate_CO_des_hollow


function gr_CO_diff_bridge_bridge_l(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_CO_diff_bridge_bridge_l

    nr_vars(:) = 0
    select case(get_species(cell + (/-2, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select

    gr_CO_diff_bridge_bridge_l = rate_CO_diff_bridge_bridge_l(nr_vars)
    return

end function gr_CO_diff_bridge_bridge_l

function rate_CO_diff_bridge_bridge_l(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_CO_diff_bridge_bridge_l
    rate_CO_diff_bridge_bridge_l = rates (CO_diff_bridge_bridge_l ) * &
    &exp  (- (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_CO_CO_bridge_bridge) + nr_vars(7) &
    &*  userpar(V_CO_CO_bridge_hollow) + nr_vars(4) * &
    &userpar(V_CO_O_bridge_bridge)  + nr_vars(8) * &
    &userpar(V_CO_O_bridge_hollow)  - (nr_vars(1) * &
    &userpar(V_CO_CO_bridge_bridge)  + nr_vars(5) * &
    &userpar(V_CO_CO_bridge_hollow)  + nr_vars(2) * &
    &userpar(V_CO_O_bridge_bridge)  + nr_vars(6) * &
    &userpar(V_CO_O_bridge_hollow)  ) ) ) * eV )  

    return

end function rate_CO_diff_bridge_bridge_l


function gr_CO_diff_bridge_bridge_r(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_CO_diff_bridge_bridge_r

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_CO_diff_bridge_bridge_r = rate_CO_diff_bridge_bridge_r(nr_vars)
    return

end function gr_CO_diff_bridge_bridge_r

function rate_CO_diff_bridge_bridge_r(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_CO_diff_bridge_bridge_r
    rate_CO_diff_bridge_bridge_r = rates (CO_diff_bridge_bridge_r ) * &
    &exp  (- (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_CO_CO_bridge_bridge) + nr_vars(7) &
    &*  userpar(V_CO_CO_bridge_hollow) + nr_vars(4) * &
    &userpar(V_CO_O_bridge_bridge)  + nr_vars(8) * &
    &userpar(V_CO_O_bridge_hollow)  - (nr_vars(1) * &
    &userpar(V_CO_CO_bridge_bridge)  + nr_vars(5) * &
    &userpar(V_CO_CO_bridge_hollow)  + nr_vars(2) * &
    &userpar(V_CO_O_bridge_bridge)  + nr_vars(6) * &
    &userpar(V_CO_O_bridge_hollow)  ) ) ) * eV )  

    return

end function rate_CO_diff_bridge_bridge_r


function gr_CO_diff_bridge_hollow(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_CO_diff_bridge_hollow

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select

    gr_CO_diff_bridge_hollow = rate_CO_diff_bridge_hollow(nr_vars)
    return

end function gr_CO_diff_bridge_hollow

function rate_CO_diff_bridge_hollow(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_CO_diff_bridge_hollow
    rate_CO_diff_bridge_hollow = rates (CO_diff_bridge_hollow ) * exp &
    &( - (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_CO_CO_hollow_bridge) + nr_vars(7) &
    &*  userpar(V_CO_CO_hollow_hollow) + nr_vars(4) * &
    &userpar(V_CO_O_hollow_bridge)  + nr_vars(8) * &
    &userpar(V_CO_O_hollow_hollow)  - (nr_vars(1) * &
    &userpar(V_CO_CO_bridge_bridge)  + nr_vars(5) * &
    &userpar(V_CO_CO_bridge_hollow)  + nr_vars(2) * &
    &userpar(V_CO_O_bridge_bridge)  + nr_vars(6) * &
    &userpar(V_CO_O_bridge_hollow)  ) ) ) * eV )  

    return

end function rate_CO_diff_bridge_hollow


function gr_CO_diff_bridge_hollow_l(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_CO_diff_bridge_hollow_l

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
            nr_vars(8) = nr_vars(8) + 1
    end select

    gr_CO_diff_bridge_hollow_l = rate_CO_diff_bridge_hollow_l(nr_vars)
    return

end function gr_CO_diff_bridge_hollow_l

function rate_CO_diff_bridge_hollow_l(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_CO_diff_bridge_hollow_l
    rate_CO_diff_bridge_hollow_l = rates (CO_diff_bridge_hollow_l ) * &
    &exp  (- (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_CO_CO_hollow_bridge) + nr_vars(7) &
    &*  userpar(V_CO_CO_hollow_hollow) + nr_vars(4) * &
    &userpar(V_CO_O_hollow_bridge)  + nr_vars(8) * &
    &userpar(V_CO_O_hollow_hollow)  - (nr_vars(1) * &
    &userpar(V_CO_CO_bridge_bridge)  + nr_vars(5) * &
    &userpar(V_CO_CO_bridge_hollow)  + nr_vars(2) * &
    &userpar(V_CO_O_bridge_bridge)  + nr_vars(6) * &
    &userpar(V_CO_O_bridge_hollow)  ) ) ) * eV )  

    return

end function rate_CO_diff_bridge_hollow_l


function gr_CO_diff_hollow_bridge(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_CO_diff_hollow_bridge

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select

    gr_CO_diff_hollow_bridge = rate_CO_diff_hollow_bridge(nr_vars)
    return

end function gr_CO_diff_hollow_bridge

function rate_CO_diff_hollow_bridge(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_CO_diff_hollow_bridge
    rate_CO_diff_hollow_bridge = rates (CO_diff_hollow_bridge ) * exp &
    &( - (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_CO_CO_bridge_bridge) + nr_vars(7) &
    &*  userpar(V_CO_CO_bridge_hollow) + nr_vars(4) * &
    &userpar(V_CO_O_bridge_bridge)  + nr_vars(8) * &
    &userpar(V_CO_O_bridge_hollow)  - (nr_vars(1) * &
    &userpar(V_CO_CO_hollow_bridge)  + nr_vars(5) * &
    &userpar(V_CO_CO_hollow_hollow)  + nr_vars(2) * &
    &userpar(V_CO_O_hollow_bridge)  + nr_vars(6) * &
    &userpar(V_CO_O_hollow_hollow)  ) ) ) * eV )  

    return

end function rate_CO_diff_hollow_bridge


function gr_CO_diff_hollow_bridge_r(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_CO_diff_hollow_bridge_r

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_CO_diff_hollow_bridge_r = rate_CO_diff_hollow_bridge_r(nr_vars)
    return

end function gr_CO_diff_hollow_bridge_r

function rate_CO_diff_hollow_bridge_r(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_CO_diff_hollow_bridge_r
    rate_CO_diff_hollow_bridge_r = rates (CO_diff_hollow_bridge_r ) * &
    &exp  (- (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_CO_CO_bridge_bridge) + nr_vars(7) &
    &*  userpar(V_CO_CO_bridge_hollow) + nr_vars(4) * &
    &userpar(V_CO_O_bridge_bridge)  + nr_vars(8) * &
    &userpar(V_CO_O_bridge_hollow)  - (nr_vars(1) * &
    &userpar(V_CO_CO_hollow_bridge)  + nr_vars(5) * &
    &userpar(V_CO_CO_hollow_hollow)  + nr_vars(2) * &
    &userpar(V_CO_O_hollow_bridge)  + nr_vars(6) * &
    &userpar(V_CO_O_hollow_hollow)  ) ) ) * eV )  

    return

end function rate_CO_diff_hollow_bridge_r


function gr_CO_diff_hollow_hollow_l(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_CO_diff_hollow_hollow_l

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select

    gr_CO_diff_hollow_hollow_l = rate_CO_diff_hollow_hollow_l(nr_vars)
    return

end function gr_CO_diff_hollow_hollow_l

function rate_CO_diff_hollow_hollow_l(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_CO_diff_hollow_hollow_l
    rate_CO_diff_hollow_hollow_l = rates (CO_diff_hollow_hollow_l ) * &
    &exp  (- (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_CO_CO_hollow_bridge) + nr_vars(7) &
    &*  userpar(V_CO_CO_hollow_hollow) + nr_vars(4) * &
    &userpar(V_CO_O_hollow_bridge)  + nr_vars(8) * &
    &userpar(V_CO_O_hollow_hollow)  - (nr_vars(1) * &
    &userpar(V_CO_CO_hollow_bridge)  + nr_vars(5) * &
    &userpar(V_CO_CO_hollow_hollow)  + nr_vars(2) * &
    &userpar(V_CO_O_hollow_bridge)  + nr_vars(6) * &
    &userpar(V_CO_O_hollow_hollow)  ) ) ) * eV )  

    return

end function rate_CO_diff_hollow_hollow_l


function gr_CO_diff_hollow_hollow_r(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_CO_diff_hollow_hollow_r

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_CO_diff_hollow_hollow_r = rate_CO_diff_hollow_hollow_r(nr_vars)
    return

end function gr_CO_diff_hollow_hollow_r

function rate_CO_diff_hollow_hollow_r(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_CO_diff_hollow_hollow_r
    rate_CO_diff_hollow_hollow_r = rates (CO_diff_hollow_hollow_r ) * &
    &exp  (- (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_CO_CO_hollow_bridge) + nr_vars(7) &
    &*  userpar(V_CO_CO_hollow_hollow) + nr_vars(4) * &
    &userpar(V_CO_O_hollow_bridge)  + nr_vars(8) * &
    &userpar(V_CO_O_hollow_hollow)  - (nr_vars(1) * &
    &userpar(V_CO_CO_hollow_bridge)  + nr_vars(5) * &
    &userpar(V_CO_CO_hollow_hollow)  + nr_vars(2) * &
    &userpar(V_CO_O_hollow_bridge)  + nr_vars(6) * &
    &userpar(V_CO_O_hollow_hollow)  ) ) ) * eV )  

    return

end function rate_CO_diff_hollow_hollow_r


function gr_CO_oxi_bridge_bridge_l(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_CO_oxi_bridge_bridge_l


    gr_CO_oxi_bridge_bridge_l = rate_CO_oxi_bridge_bridge_l()
    return

end function gr_CO_oxi_bridge_bridge_l

function rate_CO_oxi_bridge_bridge_l()


    real(kind=rdouble) :: rate_CO_oxi_bridge_bridge_l
    rate_CO_oxi_bridge_bridge_l = rates(CO_oxi_bridge_bridge_l)
    return

end function rate_CO_oxi_bridge_bridge_l


function gr_CO_oxi_bridge_bridge_r(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_CO_oxi_bridge_bridge_r


    gr_CO_oxi_bridge_bridge_r = rate_CO_oxi_bridge_bridge_r()
    return

end function gr_CO_oxi_bridge_bridge_r

function rate_CO_oxi_bridge_bridge_r()


    real(kind=rdouble) :: rate_CO_oxi_bridge_bridge_r
    rate_CO_oxi_bridge_bridge_r = rates(CO_oxi_bridge_bridge_r)
    return

end function rate_CO_oxi_bridge_bridge_r


function gr_CO_oxi_bridge_hollow(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_CO_oxi_bridge_hollow


    gr_CO_oxi_bridge_hollow = rate_CO_oxi_bridge_hollow()
    return

end function gr_CO_oxi_bridge_hollow

function rate_CO_oxi_bridge_hollow()


    real(kind=rdouble) :: rate_CO_oxi_bridge_hollow
    rate_CO_oxi_bridge_hollow = rates(CO_oxi_bridge_hollow)
    return

end function rate_CO_oxi_bridge_hollow


function gr_CO_oxi_bridge_hollow_l(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_CO_oxi_bridge_hollow_l


    gr_CO_oxi_bridge_hollow_l = rate_CO_oxi_bridge_hollow_l()
    return

end function gr_CO_oxi_bridge_hollow_l

function rate_CO_oxi_bridge_hollow_l()


    real(kind=rdouble) :: rate_CO_oxi_bridge_hollow_l
    rate_CO_oxi_bridge_hollow_l = rates(CO_oxi_bridge_hollow_l)
    return

end function rate_CO_oxi_bridge_hollow_l


function gr_CO_oxi_hollow_bridge(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_CO_oxi_hollow_bridge


    gr_CO_oxi_hollow_bridge = rate_CO_oxi_hollow_bridge()
    return

end function gr_CO_oxi_hollow_bridge

function rate_CO_oxi_hollow_bridge()


    real(kind=rdouble) :: rate_CO_oxi_hollow_bridge
    rate_CO_oxi_hollow_bridge = rates(CO_oxi_hollow_bridge)
    return

end function rate_CO_oxi_hollow_bridge


function gr_CO_oxi_hollow_bridge_r(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_CO_oxi_hollow_bridge_r


    gr_CO_oxi_hollow_bridge_r = rate_CO_oxi_hollow_bridge_r()
    return

end function gr_CO_oxi_hollow_bridge_r

function rate_CO_oxi_hollow_bridge_r()


    real(kind=rdouble) :: rate_CO_oxi_hollow_bridge_r
    rate_CO_oxi_hollow_bridge_r = rates(CO_oxi_hollow_bridge_r)
    return

end function rate_CO_oxi_hollow_bridge_r


function gr_CO_oxi_hollow_hollow_l(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_CO_oxi_hollow_hollow_l


    gr_CO_oxi_hollow_hollow_l = rate_CO_oxi_hollow_hollow_l()
    return

end function gr_CO_oxi_hollow_hollow_l

function rate_CO_oxi_hollow_hollow_l()


    real(kind=rdouble) :: rate_CO_oxi_hollow_hollow_l
    rate_CO_oxi_hollow_hollow_l = rates(CO_oxi_hollow_hollow_l)
    return

end function rate_CO_oxi_hollow_hollow_l


function gr_CO_oxi_hollow_hollow_r(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_CO_oxi_hollow_hollow_r


    gr_CO_oxi_hollow_hollow_r = rate_CO_oxi_hollow_hollow_r()
    return

end function gr_CO_oxi_hollow_hollow_r

function rate_CO_oxi_hollow_hollow_r()


    real(kind=rdouble) :: rate_CO_oxi_hollow_hollow_r
    rate_CO_oxi_hollow_hollow_r = rates(CO_oxi_hollow_hollow_r)
    return

end function rate_CO_oxi_hollow_hollow_r


function gr_O2_ads_bridge_bridge(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_O2_ads_bridge_bridge


    gr_O2_ads_bridge_bridge = rate_O2_ads_bridge_bridge()
    return

end function gr_O2_ads_bridge_bridge

function rate_O2_ads_bridge_bridge()


    real(kind=rdouble) :: rate_O2_ads_bridge_bridge
    rate_O2_ads_bridge_bridge = rates(O2_ads_bridge_bridge)
    return

end function rate_O2_ads_bridge_bridge


function gr_O2_ads_bridge_hollow(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_O2_ads_bridge_hollow


    gr_O2_ads_bridge_hollow = rate_O2_ads_bridge_hollow()
    return

end function gr_O2_ads_bridge_hollow

function rate_O2_ads_bridge_hollow()


    real(kind=rdouble) :: rate_O2_ads_bridge_hollow
    rate_O2_ads_bridge_hollow = rates(O2_ads_bridge_hollow)
    return

end function rate_O2_ads_bridge_hollow


function gr_O2_ads_hollow_bridge(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_O2_ads_hollow_bridge


    gr_O2_ads_hollow_bridge = rate_O2_ads_hollow_bridge()
    return

end function gr_O2_ads_hollow_bridge

function rate_O2_ads_hollow_bridge()


    real(kind=rdouble) :: rate_O2_ads_hollow_bridge
    rate_O2_ads_hollow_bridge = rates(O2_ads_hollow_bridge)
    return

end function rate_O2_ads_hollow_bridge


function gr_O2_ads_hollow_hollow(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_O2_ads_hollow_hollow


    gr_O2_ads_hollow_hollow = rate_O2_ads_hollow_hollow()
    return

end function gr_O2_ads_hollow_hollow

function rate_O2_ads_hollow_hollow()


    real(kind=rdouble) :: rate_O2_ads_hollow_hollow
    rate_O2_ads_hollow_hollow = rates(O2_ads_hollow_hollow)
    return

end function rate_O2_ads_hollow_hollow


function gr_O2_des_bridge_bridge_r(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_O2_des_bridge_bridge_r

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_O2_des_bridge_bridge_r = rate_O2_des_bridge_bridge_r(nr_vars)
    return

end function gr_O2_des_bridge_bridge_r

function rate_O2_des_bridge_bridge_r(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_O2_des_bridge_bridge_r
    rate_O2_des_bridge_bridge_r = rates (O2_des_bridge_bridge_r ) * &
    &exp  ((1 / (kboltzmann * userpar(T) ) ) * 2 * (nr_vars(1) * &
    &userpar(V_O_CO_bridge_bridge)  + nr_vars(3) * &
    &userpar(V_O_CO_bridge_bridge)  + nr_vars(5) * &
    &userpar(V_O_CO_bridge_hollow)  + nr_vars(7) * &
    &userpar(V_O_CO_bridge_hollow)  + nr_vars(2) * &
    &userpar(V_O_O_bridge_bridge)  + nr_vars(4) * &
    &userpar(V_O_O_bridge_bridge)  + nr_vars(6) * &
    &userpar(V_O_O_bridge_hollow)  + nr_vars(8) * &
    &userpar(V_O_O_bridge_hollow)  ) * eV )  

    return

end function rate_O2_des_bridge_bridge_r


function gr_O2_des_bridge_hollow(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_O2_des_bridge_hollow

    nr_vars(:) = 0
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select

    gr_O2_des_bridge_hollow = rate_O2_des_bridge_hollow(nr_vars)
    return

end function gr_O2_des_bridge_hollow

function rate_O2_des_bridge_hollow(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_O2_des_bridge_hollow
    rate_O2_des_bridge_hollow = rates (O2_des_bridge_hollow ) * exp ((&
    &1  / (kboltzmann * userpar(T) ) ) * 2 * (nr_vars(1) * &
    &userpar(V_O_CO_bridge_bridge)  + nr_vars(3) * &
    &userpar(V_O_CO_hollow_bridge)  + nr_vars(5) * &
    &userpar(V_O_CO_bridge_hollow)  + nr_vars(7) * &
    &userpar(V_O_CO_hollow_hollow)  + nr_vars(2) * &
    &userpar(V_O_O_bridge_bridge)  + nr_vars(4) * &
    &userpar(V_O_O_hollow_bridge)  + nr_vars(6) * &
    &userpar(V_O_O_bridge_hollow)  + nr_vars(8) * &
    &userpar(V_O_O_hollow_hollow)  ) * eV )  

    return

end function rate_O2_des_bridge_hollow


function gr_O2_des_hollow_bridge_r(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_O2_des_hollow_bridge_r

    nr_vars(:) = 0
    select case(get_species(cell + (/0, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_O2_des_hollow_bridge_r = rate_O2_des_hollow_bridge_r(nr_vars)
    return

end function gr_O2_des_hollow_bridge_r

function rate_O2_des_hollow_bridge_r(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_O2_des_hollow_bridge_r
    rate_O2_des_hollow_bridge_r = rates (O2_des_hollow_bridge_r ) * &
    &exp  ((1 / (kboltzmann * userpar(T) ) ) * 2 * (nr_vars(1) * &
    &userpar(V_O_CO_hollow_bridge)  + nr_vars(3) * &
    &userpar(V_O_CO_bridge_bridge)  + nr_vars(5) * &
    &userpar(V_O_CO_hollow_hollow)  + nr_vars(7) * &
    &userpar(V_O_CO_bridge_hollow)  + nr_vars(2) * &
    &userpar(V_O_O_hollow_bridge)  + nr_vars(4) * &
    &userpar(V_O_O_bridge_bridge)  + nr_vars(6) * &
    &userpar(V_O_O_hollow_hollow)  + nr_vars(8) * &
    &userpar(V_O_O_bridge_hollow)  ) * eV )  

    return

end function rate_O2_des_hollow_bridge_r


function gr_O2_des_hollow_hollow_r(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_O2_des_hollow_hollow_r

    nr_vars(:) = 0
    select case(get_species(cell + (/0, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_O2_des_hollow_hollow_r = rate_O2_des_hollow_hollow_r(nr_vars)
    return

end function gr_O2_des_hollow_hollow_r

function rate_O2_des_hollow_hollow_r(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_O2_des_hollow_hollow_r
    rate_O2_des_hollow_hollow_r = rates (O2_des_hollow_hollow_r ) * &
    &exp  ((1 / (kboltzmann * userpar(T) ) ) * 2 * (nr_vars(1) * &
    &userpar(V_O_CO_hollow_bridge)  + nr_vars(3) * &
    &userpar(V_O_CO_hollow_bridge)  + nr_vars(5) * &
    &userpar(V_O_CO_hollow_hollow)  + nr_vars(7) * &
    &userpar(V_O_CO_hollow_hollow)  + nr_vars(2) * &
    &userpar(V_O_O_hollow_bridge)  + nr_vars(4) * &
    &userpar(V_O_O_hollow_bridge)  + nr_vars(6) * &
    &userpar(V_O_O_hollow_hollow)  + nr_vars(8) * &
    &userpar(V_O_O_hollow_hollow)  ) * eV )  

    return

end function rate_O2_des_hollow_hollow_r


function gr_O_diff_bridge_bridge_l(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_O_diff_bridge_bridge_l

    nr_vars(:) = 0
    select case(get_species(cell + (/-2, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select

    gr_O_diff_bridge_bridge_l = rate_O_diff_bridge_bridge_l(nr_vars)
    return

end function gr_O_diff_bridge_bridge_l

function rate_O_diff_bridge_bridge_l(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_O_diff_bridge_bridge_l
    rate_O_diff_bridge_bridge_l = rates (O_diff_bridge_bridge_l ) * &
    &exp  (- (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_O_CO_bridge_bridge) + nr_vars(7) * &
    &userpar(V_O_CO_bridge_hollow)  + nr_vars(4) * &
    &userpar(V_O_O_bridge_bridge)  + nr_vars(8) * &
    &userpar(V_O_O_bridge_hollow)  - (nr_vars(1) * &
    &userpar(V_O_CO_bridge_bridge)  + nr_vars(5) * &
    &userpar(V_O_CO_bridge_hollow)  + nr_vars(2) * &
    &userpar(V_O_O_bridge_bridge)  + nr_vars(6) * &
    &userpar(V_O_O_bridge_hollow)  ) ) ) * eV )  

    return

end function rate_O_diff_bridge_bridge_l


function gr_O_diff_bridge_bridge_r(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_O_diff_bridge_bridge_r

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_O_diff_bridge_bridge_r = rate_O_diff_bridge_bridge_r(nr_vars)
    return

end function gr_O_diff_bridge_bridge_r

function rate_O_diff_bridge_bridge_r(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_O_diff_bridge_bridge_r
    rate_O_diff_bridge_bridge_r = rates (O_diff_bridge_bridge_r ) * &
    &exp  (- (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_O_CO_bridge_bridge) + nr_vars(7) * &
    &userpar(V_O_CO_bridge_hollow)  + nr_vars(4) * &
    &userpar(V_O_O_bridge_bridge)  + nr_vars(8) * &
    &userpar(V_O_O_bridge_hollow)  - (nr_vars(1) * &
    &userpar(V_O_CO_bridge_bridge)  + nr_vars(5) * &
    &userpar(V_O_CO_bridge_hollow)  + nr_vars(2) * &
    &userpar(V_O_O_bridge_bridge)  + nr_vars(6) * &
    &userpar(V_O_O_bridge_hollow)  ) ) ) * eV )  

    return

end function rate_O_diff_bridge_bridge_r


function gr_O_diff_bridge_hollow(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_O_diff_bridge_hollow

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select

    gr_O_diff_bridge_hollow = rate_O_diff_bridge_hollow(nr_vars)
    return

end function gr_O_diff_bridge_hollow

function rate_O_diff_bridge_hollow(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_O_diff_bridge_hollow
    rate_O_diff_bridge_hollow = rates (O_diff_bridge_hollow ) * exp (&
    &-  (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_O_CO_hollow_bridge) + nr_vars(7) * &
    &userpar(V_O_CO_hollow_hollow)  + nr_vars(4) * &
    &userpar(V_O_O_hollow_bridge)  + nr_vars(8) * &
    &userpar(V_O_O_hollow_hollow)  - (nr_vars(1) * &
    &userpar(V_O_CO_bridge_bridge)  + nr_vars(5) * &
    &userpar(V_O_CO_bridge_hollow)  + nr_vars(2) * &
    &userpar(V_O_O_bridge_bridge)  + nr_vars(6) * &
    &userpar(V_O_O_bridge_hollow)  ) ) ) * eV )  

    return

end function rate_O_diff_bridge_hollow


function gr_O_diff_bridge_hollow_l(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_O_diff_bridge_hollow_l

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/0, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
            nr_vars(8) = nr_vars(8) + 1
    end select

    gr_O_diff_bridge_hollow_l = rate_O_diff_bridge_hollow_l(nr_vars)
    return

end function gr_O_diff_bridge_hollow_l

function rate_O_diff_bridge_hollow_l(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_O_diff_bridge_hollow_l
    rate_O_diff_bridge_hollow_l = rates (O_diff_bridge_hollow_l ) * &
    &exp  (- (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_O_CO_hollow_bridge) + nr_vars(7) * &
    &userpar(V_O_CO_hollow_hollow)  + nr_vars(4) * &
    &userpar(V_O_O_hollow_bridge)  + nr_vars(8) * &
    &userpar(V_O_O_hollow_hollow)  - (nr_vars(1) * &
    &userpar(V_O_CO_bridge_bridge)  + nr_vars(5) * &
    &userpar(V_O_CO_bridge_hollow)  + nr_vars(2) * &
    &userpar(V_O_O_bridge_bridge)  + nr_vars(6) * &
    &userpar(V_O_O_bridge_hollow)  ) ) ) * eV )  

    return

end function rate_O_diff_bridge_hollow_l


function gr_O_diff_hollow_bridge(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_O_diff_hollow_bridge

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select

    gr_O_diff_hollow_bridge = rate_O_diff_hollow_bridge(nr_vars)
    return

end function gr_O_diff_hollow_bridge

function rate_O_diff_hollow_bridge(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_O_diff_hollow_bridge
    rate_O_diff_hollow_bridge = rates (O_diff_hollow_bridge ) * exp (&
    &-  (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_O_CO_bridge_bridge) + nr_vars(7) * &
    &userpar(V_O_CO_bridge_hollow)  + nr_vars(4) * &
    &userpar(V_O_O_bridge_bridge)  + nr_vars(8) * &
    &userpar(V_O_O_bridge_hollow)  - (nr_vars(1) * &
    &userpar(V_O_CO_hollow_bridge)  + nr_vars(5) * &
    &userpar(V_O_CO_hollow_hollow)  + nr_vars(2) * &
    &userpar(V_O_O_hollow_bridge)  + nr_vars(6) * &
    &userpar(V_O_O_hollow_hollow)  ) ) ) * eV )  

    return

end function rate_O_diff_hollow_bridge


function gr_O_diff_hollow_bridge_r(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_O_diff_hollow_bridge_r

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_O_diff_hollow_bridge_r = rate_O_diff_hollow_bridge_r(nr_vars)
    return

end function gr_O_diff_hollow_bridge_r

function rate_O_diff_hollow_bridge_r(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_O_diff_hollow_bridge_r
    rate_O_diff_hollow_bridge_r = rates (O_diff_hollow_bridge_r ) * &
    &exp  (- (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_O_CO_bridge_bridge) + nr_vars(7) * &
    &userpar(V_O_CO_bridge_hollow)  + nr_vars(4) * &
    &userpar(V_O_O_bridge_bridge)  + nr_vars(8) * &
    &userpar(V_O_O_bridge_hollow)  - (nr_vars(1) * &
    &userpar(V_O_CO_hollow_bridge)  + nr_vars(5) * &
    &userpar(V_O_CO_hollow_hollow)  + nr_vars(2) * &
    &userpar(V_O_O_hollow_bridge)  + nr_vars(6) * &
    &userpar(V_O_O_hollow_hollow)  ) ) ) * eV )  

    return

end function rate_O_diff_hollow_bridge_r


function gr_O_diff_hollow_hollow_l(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_O_diff_hollow_hollow_l

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/-2, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select

    gr_O_diff_hollow_hollow_l = rate_O_diff_hollow_hollow_l(nr_vars)
    return

end function gr_O_diff_hollow_hollow_l

function rate_O_diff_hollow_hollow_l(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_O_diff_hollow_hollow_l
    rate_O_diff_hollow_hollow_l = rates (O_diff_hollow_hollow_l ) * &
    &exp  (- (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_O_CO_hollow_bridge) + nr_vars(7) * &
    &userpar(V_O_CO_hollow_hollow)  + nr_vars(4) * &
    &userpar(V_O_O_hollow_bridge)  + nr_vars(8) * &
    &userpar(V_O_O_hollow_hollow)  - (nr_vars(1) * &
    &userpar(V_O_CO_hollow_bridge)  + nr_vars(5) * &
    &userpar(V_O_CO_hollow_hollow)  + nr_vars(2) * &
    &userpar(V_O_O_hollow_bridge)  + nr_vars(6) * &
    &userpar(V_O_O_hollow_hollow)  ) ) ) * eV )  

    return

end function rate_O_diff_hollow_hollow_l


function gr_O_diff_hollow_hollow_r(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    integer(kind=iint), dimension(8) :: nr_vars
    real(kind=rdouble) :: gr_O_diff_hollow_hollow_r

    nr_vars(:) = 0
    select case(get_species(cell + (/-1, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(5) = nr_vars(5) + 1
        case(O)
            nr_vars(6) = nr_vars(6) + 1
    end select
    select case(get_species(cell + (/0, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(1) = nr_vars(1) + 1
        case(O)
            nr_vars(2) = nr_vars(2) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, pdo_hollow/)))
        case(CO)
            nr_vars(7) = nr_vars(7) + 1
        case(O)
            nr_vars(8) = nr_vars(8) + 1
    end select
    select case(get_species(cell + (/2, 0, 0, pdo_bridge/)))
        case(CO)
            nr_vars(3) = nr_vars(3) + 1
        case(O)
            nr_vars(4) = nr_vars(4) + 1
    end select

    gr_O_diff_hollow_hollow_r = rate_O_diff_hollow_hollow_r(nr_vars)
    return

end function gr_O_diff_hollow_hollow_r

function rate_O_diff_hollow_hollow_r(nr_vars)

    integer(kind=iint), dimension(8), intent(in) :: nr_vars

    real(kind=rdouble) :: rate_O_diff_hollow_hollow_r
    rate_O_diff_hollow_hollow_r = rates (O_diff_hollow_hollow_r ) * &
    &exp  (- (1 / (kboltzmann * userpar(T) ) ) * 2 * (max (0.0 , &
    &nr_vars(3)  * userpar(V_O_CO_hollow_bridge) + nr_vars(7) * &
    &userpar(V_O_CO_hollow_hollow)  + nr_vars(4) * &
    &userpar(V_O_O_hollow_bridge)  + nr_vars(8) * &
    &userpar(V_O_O_hollow_hollow)  - (nr_vars(1) * &
    &userpar(V_O_CO_hollow_bridge)  + nr_vars(5) * &
    &userpar(V_O_CO_hollow_hollow)  + nr_vars(2) * &
    &userpar(V_O_O_hollow_bridge)  + nr_vars(6) * &
    &userpar(V_O_O_hollow_hollow)  ) ) ) * eV )  

    return

end function rate_O_diff_hollow_hollow_r


end module proclist_pars
