!  This file was generated by kMOS (kMC modelling on steroids)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2013.
!  The model was written by Juan M. Lorenzi.

!  This file is part of kmos.
!
!  kmos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
!****h* kmos/proclist
! FUNCTION
!    Implements the kMC process list.
!
!******


module proclist_constants
use kind_values
use lattice, only: &
    pdo, &
    pdo_bridge, &
    pdo_hollow, &
    get_species


implicit none



 ! Species constants



integer(kind=iint), parameter, public :: nr_of_species = 3
integer(kind=iint), parameter, public :: CO = 0
integer(kind=iint), parameter, public :: O = 1
integer(kind=iint), parameter, public :: empty = 2
integer(kind=iint), public :: default_species = empty

! Process constants

integer(kind=iint), parameter, public :: CO_ads_bridge = 1
integer(kind=iint), parameter, public :: CO_ads_hollow = 2
integer(kind=iint), parameter, public :: CO_des_bridge = 3
integer(kind=iint), parameter, public :: CO_des_hollow = 4
integer(kind=iint), parameter, public :: CO_diff_bridge_bridge_l = 5
integer(kind=iint), parameter, public :: CO_diff_bridge_bridge_r = 6
integer(kind=iint), parameter, public :: CO_diff_bridge_hollow = 7
integer(kind=iint), parameter, public :: CO_diff_bridge_hollow_l = 8
integer(kind=iint), parameter, public :: CO_diff_hollow_bridge = 9
integer(kind=iint), parameter, public :: CO_diff_hollow_bridge_r = 10
integer(kind=iint), parameter, public :: CO_diff_hollow_hollow_l = 11
integer(kind=iint), parameter, public :: CO_diff_hollow_hollow_r = 12
integer(kind=iint), parameter, public :: CO_oxi_bridge_bridge_l = 13
integer(kind=iint), parameter, public :: CO_oxi_bridge_bridge_r = 14
integer(kind=iint), parameter, public :: CO_oxi_bridge_hollow = 15
integer(kind=iint), parameter, public :: CO_oxi_bridge_hollow_l = 16
integer(kind=iint), parameter, public :: CO_oxi_hollow_bridge = 17
integer(kind=iint), parameter, public :: CO_oxi_hollow_bridge_r = 18
integer(kind=iint), parameter, public :: CO_oxi_hollow_hollow_l = 19
integer(kind=iint), parameter, public :: CO_oxi_hollow_hollow_r = 20
integer(kind=iint), parameter, public :: O2_ads_bridge_bridge = 21
integer(kind=iint), parameter, public :: O2_ads_bridge_hollow = 22
integer(kind=iint), parameter, public :: O2_ads_hollow_bridge = 23
integer(kind=iint), parameter, public :: O2_ads_hollow_hollow = 24
integer(kind=iint), parameter, public :: O2_des_bridge_bridge_r = 25
integer(kind=iint), parameter, public :: O2_des_bridge_hollow = 26
integer(kind=iint), parameter, public :: O2_des_hollow_bridge_r = 27
integer(kind=iint), parameter, public :: O2_des_hollow_hollow_r = 28
integer(kind=iint), parameter, public :: O_diff_bridge_bridge_l = 29
integer(kind=iint), parameter, public :: O_diff_bridge_bridge_r = 30
integer(kind=iint), parameter, public :: O_diff_bridge_hollow = 31
integer(kind=iint), parameter, public :: O_diff_bridge_hollow_l = 32
integer(kind=iint), parameter, public :: O_diff_hollow_bridge = 33
integer(kind=iint), parameter, public :: O_diff_hollow_bridge_r = 34
integer(kind=iint), parameter, public :: O_diff_hollow_hollow_l = 35
integer(kind=iint), parameter, public :: O_diff_hollow_hollow_r = 36

end module proclist_constants
