!  This file was generated by kMOS (kMC modelling on steroids)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2013.
!  The model was written by Juan M. Lorenzi.

!  This file is part of kmos.
!
!  kmos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
!****h* kmos/proclist
! FUNCTION
!    Implements the kMC process list.
!
!******


module proclist_constants
use kind_values
use lattice, only: &
    square, &
    square_default, &
    get_species


implicit none



 ! Species constants



integer(kind=iint), parameter, public :: nr_of_species = 3
integer(kind=iint), parameter, public :: CO = 0
integer(kind=iint), parameter, public :: O = 1
integer(kind=iint), parameter, public :: empty = 2
integer(kind=iint), public :: default_species = empty

! Process constants

integer(kind=iint), parameter, public :: CO_ads = 1
integer(kind=iint), parameter, public :: CO_des = 2
integer(kind=iint), parameter, public :: CO_oxidation_00 = 3
integer(kind=iint), parameter, public :: CO_oxidation_01 = 4
integer(kind=iint), parameter, public :: CO_oxidation_02 = 5
integer(kind=iint), parameter, public :: CO_oxidation_03 = 6
integer(kind=iint), parameter, public :: O2_des_right = 7
integer(kind=iint), parameter, public :: O2_des_up = 8
integer(kind=iint), parameter, public :: O_ads_00 = 9
integer(kind=iint), parameter, public :: O_ads_01 = 10

end module proclist_constants
