!  This file was generated by kMOS (kMC modelling on steroids)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2010.
!  The model was written by Max J. Hoffmann.

!  This file is part of kmos.
!
!  kmos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA

module proclist

use kind_values
use base, only: &
    update_accum_rate, &
    determine_procsite, &
    update_clocks, &
    increment_procstat
use lattice, only: &
    lattice_allocate_system => allocate_system ,&
    nr2ruo2, &
    ruo22nr, &
    ruo2_add_proc, &
    ruo2_can_do, &
    ruo2_replace_species, &
    ruo2_del_proc, &
    ruo2_get_species, &
    co, &
    oxygen, &
    empty

implicit none

! Process constants
integer(kind=iint), parameter, public :: co_adsorption_bridge = 1
integer(kind=iint), parameter, public :: co_adsorption_cus = 2
integer(kind=iint), parameter, public :: co_desorption_bridge = 3
integer(kind=iint), parameter, public :: co_desorption_cus = 4
integer(kind=iint), parameter, public :: co_diffusion_bridge_bridge_down = 5
integer(kind=iint), parameter, public :: co_diffusion_bridge_bridge_up = 6
integer(kind=iint), parameter, public :: co_diffusion_bridge_cus_left = 7
integer(kind=iint), parameter, public :: co_diffusion_bridge_cus_right = 8
integer(kind=iint), parameter, public :: co_diffusion_cus_bridge_left = 9
integer(kind=iint), parameter, public :: co_diffusion_cus_bridge_right = 10
integer(kind=iint), parameter, public :: co_diffusion_cus_cus_down = 11
integer(kind=iint), parameter, public :: co_diffusion_cus_cus_up = 12
integer(kind=iint), parameter, public :: oxygen_adsorption_bridge_bridge = 13
integer(kind=iint), parameter, public :: oxygen_adsorption_bridge_cus_left = 14
integer(kind=iint), parameter, public :: oxygen_adsorption_bridge_cus_right = 15
integer(kind=iint), parameter, public :: oxygen_adsorption_cus_cus = 16
integer(kind=iint), parameter, public :: oxygen_desorption_bridge_bridge = 17
integer(kind=iint), parameter, public :: oxygen_desorption_bridge_cus_left = 18
integer(kind=iint), parameter, public :: oxygen_desorption_bridge_cus_right = 19
integer(kind=iint), parameter, public :: oxygen_desorption_cus_cus = 20
integer(kind=iint), parameter, public :: oxygen_diffusion_bridge_bridge_down = 21
integer(kind=iint), parameter, public :: oxygen_diffusion_bridge_bridge_up = 22
integer(kind=iint), parameter, public :: oxygen_diffusion_bridge_cus_left = 23
integer(kind=iint), parameter, public :: oxygen_diffusion_bridge_cus_right = 24
integer(kind=iint), parameter, public :: oxygen_diffusion_cus_bridge_left = 25
integer(kind=iint), parameter, public :: oxygen_diffusion_cus_bridge_right = 26
integer(kind=iint), parameter, public :: oxygen_diffusion_cus_cus_down = 27
integer(kind=iint), parameter, public :: oxygen_diffusion_cus_cus_up = 28
integer(kind=iint), parameter, public :: reaction_oxygen_bridge_co_bridge_down = 29
integer(kind=iint), parameter, public :: reaction_oxygen_bridge_co_bridge_up = 30
integer(kind=iint), parameter, public :: reaction_oxygen_bridge_co_cus_left = 31
integer(kind=iint), parameter, public :: reaction_oxygen_bridge_co_cus_right = 32
integer(kind=iint), parameter, public :: reaction_oxygen_cus_co_bridge_left = 33
integer(kind=iint), parameter, public :: reaction_oxygen_cus_co_bridge_right = 34
integer(kind=iint), parameter, public :: reaction_oxygen_cus_co_cus_down = 35
integer(kind=iint), parameter, public :: reaction_oxygen_cus_co_cus_up = 36

integer(kind=iint), parameter, public :: nr_of_proc = 36
character(len=2000), dimension(36)  :: processes, rates

contains

subroutine init(input_system_size, system_name)
    integer(kind=iint), dimension(2), intent(in) :: input_system_size
    character(len=400), intent(in) :: system_name


    print *,"This kMC Model 'my_model' was written by Max J. Hoffmann"
    print *,"and implemented with the help of kmos, which is distributed under "
    print *,"GNU/GPL Version 3 (C) Max J. Hoffmann mjhoffmann@gmail.com."
    print *,"Currently kmos is a very alphaish stage and there is"
    print *,"ABSOLUTELY NO WARRANTY for correctness."
    print *,"Please check back with the author prior to using results in publication."
    call lattice_allocate_system(nr_of_proc, input_system_size, system_name)

    processes(1) = 'co_adsorption_bridge'
    rates(1) = '10**8'
    processes(2) = 'co_adsorption_cus'
    rates(2) = '10**8'
    processes(3) = 'co_desorption_bridge'
    rates(3) = ''
    processes(4) = 'co_desorption_cus'
    rates(4) = ''
    processes(5) = 'co_diffusion_bridge_bridge_down'
    rates(5) = '10**8'
    processes(6) = 'co_diffusion_bridge_bridge_up'
    rates(6) = '10**8'
    processes(7) = 'co_diffusion_bridge_cus_left'
    rates(7) = ''
    processes(8) = 'co_diffusion_bridge_cus_right'
    rates(8) = ''
    processes(9) = 'co_diffusion_cus_bridge_left'
    rates(9) = ''
    processes(10) = 'co_diffusion_cus_bridge_right'
    rates(10) = ''
    processes(11) = 'co_diffusion_cus_cus_down'
    rates(11) = ''
    processes(12) = 'co_diffusion_cus_cus_up'
    rates(12) = ''
    processes(13) = 'oxygen_adsorption_bridge_bridge'
    rates(13) = ''
    processes(14) = 'oxygen_adsorption_bridge_cus_left'
    rates(14) = ''
    processes(15) = 'oxygen_adsorption_bridge_cus_right'
    rates(15) = ''
    processes(16) = 'oxygen_adsorption_cus_cus'
    rates(16) = ''
    processes(17) = 'oxygen_desorption_bridge_bridge'
    rates(17) = ''
    processes(18) = 'oxygen_desorption_bridge_cus_left'
    rates(18) = ''
    processes(19) = 'oxygen_desorption_bridge_cus_right'
    rates(19) = ''
    processes(20) = 'oxygen_desorption_cus_cus'
    rates(20) = ''
    processes(21) = 'oxygen_diffusion_bridge_bridge_down'
    rates(21) = ''
    processes(22) = 'oxygen_diffusion_bridge_bridge_up'
    rates(22) = ''
    processes(23) = 'oxygen_diffusion_bridge_cus_left'
    rates(23) = ''
    processes(24) = 'oxygen_diffusion_bridge_cus_right'
    rates(24) = ''
    processes(25) = 'oxygen_diffusion_cus_bridge_left'
    rates(25) = ''
    processes(26) = 'oxygen_diffusion_cus_bridge_right'
    rates(26) = ''
    processes(27) = 'oxygen_diffusion_cus_cus_down'
    rates(27) = ''
    processes(28) = 'oxygen_diffusion_cus_cus_up'
    rates(28) = ''
    processes(29) = 'reaction_oxygen_bridge_co_bridge_down'
    rates(29) = ''
    processes(30) = 'reaction_oxygen_bridge_co_bridge_up'
    rates(30) = ''
    processes(31) = 'reaction_oxygen_bridge_co_cus_left'
    rates(31) = ''
    processes(32) = 'reaction_oxygen_bridge_co_cus_right'
    rates(32) = ''
    processes(33) = 'reaction_oxygen_cus_co_bridge_left'
    rates(33) = ''
    processes(34) = 'reaction_oxygen_cus_co_bridge_right'
    rates(34) = ''
    processes(35) = 'reaction_oxygen_cus_co_cus_down'
    rates(35) = ''
    processes(36) = 'reaction_oxygen_cus_co_cus_up'
    rates(36) = ''
end subroutine init


subroutine get_rate_char(process_nr, char_slot, process_name)
    integer(kind=iint), intent(in) :: process_nr, char_slot
    character,  intent(out) :: process_name

    process_name = rates(process_nr)(char_slot:char_slot)

end subroutine get_rate_char


subroutine get_process_char(process_nr, char_slot, process_name)
    integer(kind=iint), intent(in) :: process_nr, char_slot
    character,  intent(out) :: process_name

    process_name = processes(process_nr)(char_slot:char_slot)

end subroutine get_process_char


subroutine do_kmc_step()
    !---------------internal variables---------------
    integer(kind=iint), dimension(2)  :: pdo_site, pd100_site
    real(kind=rsingle) :: ran_proc, ran_time, ran_site
    integer(kind=iint) :: nr_site, proc_nr

    ! Draw 3 random numbers
    call random_number(ran_time)
        call random_number(ran_proc)
    call random_number(ran_site)
    ! Update the accumulated process rates
    call update_accum_rate ! @libkmc
    ! Determine the process and site
    call determine_procsite(ran_proc, ran_time, proc_nr, nr_site) ! @libkmc

    call run_proc_nr(proc_nr, nr_site)
    call update_clocks(ran_time)

end subroutine do_kmc_step



subroutine run_proc_nr(proc, site)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in) :: proc
    integer(kind=iint), intent(in) :: site

    !-----------------Internal variables-------------------


    integer(kind=iint),  dimension(2) :: ruo2_site
    ! Update process counter
    call increment_procstat(proc)

    select case(proc)
    case (co_adsorption_bridge)! #1
        call nr2ruo2(site, ruo2_site)
        call put_co_bridge(ruo2_site)

    case (co_adsorption_cus)! #2
        call nr2ruo2(site, ruo2_site)
        call put_co_cus(ruo2_site)

    case (co_desorption_bridge)! #3
        call nr2ruo2(site, ruo2_site)
        call take_co_bridge(ruo2_site)

    case (co_desorption_cus)! #4
        call nr2ruo2(site, ruo2_site)
        call take_co_cus(ruo2_site)

    case (co_diffusion_bridge_bridge_down)! #5
        call nr2ruo2(site, ruo2_site)
        call take_co_bridge(ruo2_site)
        call put_co_bridge(ruo2_site+(/0, -1/))

    case (co_diffusion_bridge_bridge_up)! #6
        call nr2ruo2(site, ruo2_site)
        call take_co_bridge(ruo2_site)
        call put_co_bridge(ruo2_site+(/0, 1/))

    case (co_diffusion_bridge_cus_left)! #7
        call nr2ruo2(site, ruo2_site)
        call take_co_bridge(ruo2_site)
        call put_co_cus(ruo2_site+(/-1, 0/))

    case (co_diffusion_bridge_cus_right)! #8
        call nr2ruo2(site, ruo2_site)
        call take_co_bridge(ruo2_site)
        call put_co_cus(ruo2_site+(/1, 0/))

    case (co_diffusion_cus_bridge_left)! #9
        call nr2ruo2(site, ruo2_site)
        call take_co_cus(ruo2_site)
        call put_co_bridge(ruo2_site+(/-1, 0/))

    case (co_diffusion_cus_bridge_right)! #10
        call nr2ruo2(site, ruo2_site)
        call take_co_cus(ruo2_site)
        call put_co_bridge(ruo2_site+(/1, 0/))

    case (co_diffusion_cus_cus_down)! #11
        call nr2ruo2(site, ruo2_site)
        call take_co_cus(ruo2_site)
        call put_co_cus(ruo2_site+(/0, -1/))

    case (co_diffusion_cus_cus_up)! #12
        call nr2ruo2(site, ruo2_site)
        call take_co_cus(ruo2_site)
        call put_co_cus(ruo2_site+(/0, 1/))

    case (oxygen_adsorption_bridge_bridge)! #13
        call nr2ruo2(site, ruo2_site)
        call put_oxygen_bridge(ruo2_site)
        call put_oxygen_bridge(ruo2_site+(/0, 1/))

    case (oxygen_adsorption_bridge_cus_left)! #14
        call nr2ruo2(site, ruo2_site)
        call put_oxygen_bridge(ruo2_site)
        call put_oxygen_cus(ruo2_site+(/-1, 0/))

    case (oxygen_adsorption_bridge_cus_right)! #15
        call nr2ruo2(site, ruo2_site)
        call put_oxygen_bridge(ruo2_site)
        call put_oxygen_cus(ruo2_site+(/1, 0/))

    case (oxygen_adsorption_cus_cus)! #16
        call nr2ruo2(site, ruo2_site)
        call put_oxygen_cus(ruo2_site)
        call put_oxygen_cus(ruo2_site+(/0, 1/))

    case (oxygen_desorption_bridge_bridge)! #17
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_bridge(ruo2_site)
        call take_oxygen_bridge(ruo2_site+(/0, 1/))

    case (oxygen_desorption_bridge_cus_left)! #18
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_bridge(ruo2_site)
        call take_oxygen_cus(ruo2_site+(/-1, 0/))

    case (oxygen_desorption_bridge_cus_right)! #19
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_bridge(ruo2_site)
        call take_oxygen_cus(ruo2_site+(/1, 0/))

    case (oxygen_desorption_cus_cus)! #20
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_cus(ruo2_site)
        call take_oxygen_cus(ruo2_site+(/0, 1/))

    case (oxygen_diffusion_bridge_bridge_down)! #21
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_bridge(ruo2_site)
        call put_oxygen_bridge(ruo2_site+(/0, -1/))

    case (oxygen_diffusion_bridge_bridge_up)! #22
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_bridge(ruo2_site)
        call put_oxygen_bridge(ruo2_site+(/0, 1/))

    case (oxygen_diffusion_bridge_cus_left)! #23
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_bridge(ruo2_site)
        call put_oxygen_cus(ruo2_site+(/-1, 0/))

    case (oxygen_diffusion_bridge_cus_right)! #24
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_bridge(ruo2_site)
        call put_oxygen_cus(ruo2_site+(/1, 0/))

    case (oxygen_diffusion_cus_bridge_left)! #25
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_cus(ruo2_site)
        call put_oxygen_bridge(ruo2_site+(/-1, 0/))

    case (oxygen_diffusion_cus_bridge_right)! #26
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_cus(ruo2_site)
        call put_oxygen_bridge(ruo2_site+(/1, 0/))

    case (oxygen_diffusion_cus_cus_down)! #27
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_cus(ruo2_site)
        call put_oxygen_cus(ruo2_site+(/0, -1/))

    case (oxygen_diffusion_cus_cus_up)! #28
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_cus(ruo2_site)
        call put_oxygen_cus(ruo2_site+(/0, 1/))

    case (reaction_oxygen_bridge_co_bridge_down)! #29
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_bridge(ruo2_site)
        call take_co_bridge(ruo2_site+(/0, -1/))

    case (reaction_oxygen_bridge_co_bridge_up)! #30
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_bridge(ruo2_site)
        call take_co_bridge(ruo2_site+(/0, 1/))

    case (reaction_oxygen_bridge_co_cus_left)! #31
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_bridge(ruo2_site)
        call take_co_cus(ruo2_site+(/-1, 0/))

    case (reaction_oxygen_bridge_co_cus_right)! #32
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_bridge(ruo2_site)
        call take_co_cus(ruo2_site+(/1, 0/))

    case (reaction_oxygen_cus_co_bridge_left)! #33
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_cus(ruo2_site)
        call take_co_bridge(ruo2_site+(/-1, 0/))

    case (reaction_oxygen_cus_co_bridge_right)! #34
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_cus(ruo2_site)
        call take_co_bridge(ruo2_site+(/1, 0/))

    case (reaction_oxygen_cus_co_cus_down)! #35
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_cus(ruo2_site)
        call take_co_cus(ruo2_site+(/0, -1/))

    case (reaction_oxygen_cus_co_cus_up)! #36
        call nr2ruo2(site, ruo2_site)
        call take_oxygen_cus(ruo2_site)
        call take_co_cus(ruo2_site+(/0, 1/))

    case default
        print *,"my_model/run_proc_nr: we should not get here!",proc
    endselect

end subroutine run_proc_nr


subroutine put_co_bridge(site)

    integer(kind=iint), dimension(2), intent(in) :: site
    logical :: can

    integer(kind=iint) :: nr

    call ruo22nr(site, nr)

    ! lattice updates
    call ruo2_replace_species(site, empty, co)
    ! book keeping updates
    call ruo2_can_do(co_adsorption_bridge, site, can=can)
    if(can)then
        call ruo2_del_proc(co_adsorption_bridge, site)
    end if
    call check_co_desorption_bridge(site, can=can)
    if(can)then
        call ruo2_add_proc(co_desorption_bridge, site)
    end if
    call check_co_diffusion_bridge_bridge_down(site, can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_bridge_bridge_down, site)
    end if
    call ruo2_can_do(co_diffusion_bridge_bridge_down, site-(/0, -1/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_bridge_bridge_down, site-(/0, -1/))
    end if
    call check_co_diffusion_bridge_bridge_up(site, can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_bridge_bridge_up, site)
    end if
    call ruo2_can_do(co_diffusion_bridge_bridge_up, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_bridge_bridge_up, site-(/0, 1/))
    end if
    call check_co_diffusion_bridge_cus_left(site, can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_bridge_cus_left, site)
    end if
    call check_co_diffusion_bridge_cus_right(site, can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_bridge_cus_right, site)
    end if
    call ruo2_can_do(co_diffusion_cus_bridge_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_cus_bridge_left, site-(/-1, 0/))
    end if
    call ruo2_can_do(co_diffusion_cus_bridge_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_cus_bridge_right, site-(/1, 0/))
    end if
    call ruo2_can_do(oxygen_adsorption_bridge_bridge, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_bridge, site)
    end if
    call ruo2_can_do(oxygen_adsorption_bridge_bridge, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_bridge, site-(/0, 1/))
    end if
    call ruo2_can_do(oxygen_adsorption_bridge_cus_left, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_cus_left, site)
    end if
    call ruo2_can_do(oxygen_adsorption_bridge_cus_right, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_cus_right, site)
    end if
    call ruo2_can_do(oxygen_diffusion_bridge_bridge_down, site-(/0, -1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_bridge_down, site-(/0, -1/))
    end if
    call ruo2_can_do(oxygen_diffusion_bridge_bridge_up, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_bridge_up, site-(/0, 1/))
    end if
    call ruo2_can_do(oxygen_diffusion_cus_bridge_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_cus_bridge_left, site-(/-1, 0/))
    end if
    call ruo2_can_do(oxygen_diffusion_cus_bridge_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_cus_bridge_right, site-(/1, 0/))
    end if
    call check_reaction_oxygen_bridge_co_bridge_down(site-(/0, -1/), can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_bridge_co_bridge_down, site-(/0, -1/))
    end if
    call check_reaction_oxygen_bridge_co_bridge_up(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_bridge_co_bridge_up, site-(/0, 1/))
    end if
    call check_reaction_oxygen_cus_co_bridge_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_cus_co_bridge_left, site-(/-1, 0/))
    end if
    call check_reaction_oxygen_cus_co_bridge_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_cus_co_bridge_right, site-(/1, 0/))
    end if

end subroutine put_co_bridge

subroutine put_co_cus(site)

    integer(kind=iint), dimension(2), intent(in) :: site
    logical :: can

    integer(kind=iint) :: nr

    call ruo22nr(site, nr)

    ! lattice updates
    call ruo2_replace_species(site, empty, co)
    ! book keeping updates
    call ruo2_can_do(co_adsorption_cus, site, can=can)
    if(can)then
        call ruo2_del_proc(co_adsorption_cus, site)
    end if
    call check_co_desorption_cus(site, can=can)
    if(can)then
        call ruo2_add_proc(co_desorption_cus, site)
    end if
    call ruo2_can_do(co_diffusion_bridge_cus_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_bridge_cus_left, site-(/-1, 0/))
    end if
    call ruo2_can_do(co_diffusion_bridge_cus_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_bridge_cus_right, site-(/1, 0/))
    end if
    call check_co_diffusion_cus_bridge_left(site, can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_cus_bridge_left, site)
    end if
    call check_co_diffusion_cus_bridge_right(site, can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_cus_bridge_right, site)
    end if
    call check_co_diffusion_cus_cus_down(site, can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_cus_cus_down, site)
    end if
    call ruo2_can_do(co_diffusion_cus_cus_down, site-(/0, -1/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_cus_cus_down, site-(/0, -1/))
    end if
    call check_co_diffusion_cus_cus_up(site, can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_cus_cus_up, site)
    end if
    call ruo2_can_do(co_diffusion_cus_cus_up, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_cus_cus_up, site-(/0, 1/))
    end if
    call ruo2_can_do(oxygen_adsorption_bridge_cus_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_cus_left, site-(/-1, 0/))
    end if
    call ruo2_can_do(oxygen_adsorption_bridge_cus_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_cus_right, site-(/1, 0/))
    end if
    call ruo2_can_do(oxygen_adsorption_cus_cus, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_cus_cus, site)
    end if
    call ruo2_can_do(oxygen_adsorption_cus_cus, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_cus_cus, site-(/0, 1/))
    end if
    call ruo2_can_do(oxygen_diffusion_bridge_cus_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_cus_left, site-(/-1, 0/))
    end if
    call ruo2_can_do(oxygen_diffusion_bridge_cus_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_cus_right, site-(/1, 0/))
    end if
    call ruo2_can_do(oxygen_diffusion_cus_cus_down, site-(/0, -1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_cus_cus_down, site-(/0, -1/))
    end if
    call ruo2_can_do(oxygen_diffusion_cus_cus_up, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_cus_cus_up, site-(/0, 1/))
    end if
    call check_reaction_oxygen_bridge_co_cus_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_bridge_co_cus_left, site-(/-1, 0/))
    end if
    call check_reaction_oxygen_bridge_co_cus_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_bridge_co_cus_right, site-(/1, 0/))
    end if
    call check_reaction_oxygen_cus_co_cus_down(site-(/0, -1/), can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_cus_co_cus_down, site-(/0, -1/))
    end if
    call check_reaction_oxygen_cus_co_cus_up(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_cus_co_cus_up, site-(/0, 1/))
    end if

end subroutine put_co_cus

subroutine take_co_bridge(site)

    integer(kind=iint), dimension(2), intent(in) :: site
    logical :: can

    integer(kind=iint) :: nr

    call ruo22nr(site, nr)

    ! lattice updates
    call ruo2_replace_species(site, co, empty)
    ! book keeping updates
    call check_co_adsorption_bridge(site, can=can)
    if(can)then
        call ruo2_add_proc(co_adsorption_bridge, site)
    end if

    call ruo2_can_do(co_desorption_bridge, site, can=can)
    if(can)then
        call ruo2_del_proc(co_desorption_bridge, site)
    end if

    call ruo2_can_do(co_diffusion_bridge_bridge_down, site, can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_bridge_bridge_down, site)
    end if

    call check_co_diffusion_bridge_bridge_down(site-(/0, -1/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_bridge_bridge_down, site-(/0, -1/))
    end if

    call ruo2_can_do(co_diffusion_bridge_bridge_up, site, can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_bridge_bridge_up, site)
    end if

    call check_co_diffusion_bridge_bridge_up(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_bridge_bridge_up, site-(/0, 1/))
    end if

    call ruo2_can_do(co_diffusion_bridge_cus_left, site, can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_bridge_cus_left, site)
    end if

    call ruo2_can_do(co_diffusion_bridge_cus_right, site, can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_bridge_cus_right, site)
    end if

    call check_co_diffusion_cus_bridge_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_cus_bridge_left, site-(/-1, 0/))
    end if

    call check_co_diffusion_cus_bridge_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_cus_bridge_right, site-(/1, 0/))
    end if

    call check_oxygen_adsorption_bridge_bridge(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_bridge, site)
    end if

    call check_oxygen_adsorption_bridge_bridge(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_bridge, site-(/0, 1/))
    end if

    call check_oxygen_adsorption_bridge_cus_left(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_cus_left, site)
    end if

    call check_oxygen_adsorption_bridge_cus_right(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_cus_right, site)
    end if

    call check_oxygen_diffusion_bridge_bridge_down(site-(/0, -1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_bridge_down, site-(/0, -1/))
    end if

    call check_oxygen_diffusion_bridge_bridge_up(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_bridge_up, site-(/0, 1/))
    end if

    call check_oxygen_diffusion_cus_bridge_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_cus_bridge_left, site-(/-1, 0/))
    end if

    call check_oxygen_diffusion_cus_bridge_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_cus_bridge_right, site-(/1, 0/))
    end if

    call ruo2_can_do(reaction_oxygen_bridge_co_bridge_down, site-(/0, -1/), can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_bridge_co_bridge_down, site-(/0, -1/))
    end if

    call ruo2_can_do(reaction_oxygen_bridge_co_bridge_up, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_bridge_co_bridge_up, site-(/0, 1/))
    end if

    call ruo2_can_do(reaction_oxygen_cus_co_bridge_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_cus_co_bridge_left, site-(/-1, 0/))
    end if

    call ruo2_can_do(reaction_oxygen_cus_co_bridge_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_cus_co_bridge_right, site-(/1, 0/))
    end if


end subroutine take_co_bridge

subroutine take_co_cus(site)

    integer(kind=iint), dimension(2), intent(in) :: site
    logical :: can

    integer(kind=iint) :: nr

    call ruo22nr(site, nr)

    ! lattice updates
    call ruo2_replace_species(site, co, empty)
    ! book keeping updates
    call check_co_adsorption_cus(site, can=can)
    if(can)then
        call ruo2_add_proc(co_adsorption_cus, site)
    end if

    call ruo2_can_do(co_desorption_cus, site, can=can)
    if(can)then
        call ruo2_del_proc(co_desorption_cus, site)
    end if

    call check_co_diffusion_bridge_cus_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_bridge_cus_left, site-(/-1, 0/))
    end if

    call check_co_diffusion_bridge_cus_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_bridge_cus_right, site-(/1, 0/))
    end if

    call ruo2_can_do(co_diffusion_cus_bridge_left, site, can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_cus_bridge_left, site)
    end if

    call ruo2_can_do(co_diffusion_cus_bridge_right, site, can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_cus_bridge_right, site)
    end if

    call ruo2_can_do(co_diffusion_cus_cus_down, site, can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_cus_cus_down, site)
    end if

    call check_co_diffusion_cus_cus_down(site-(/0, -1/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_cus_cus_down, site-(/0, -1/))
    end if

    call ruo2_can_do(co_diffusion_cus_cus_up, site, can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_cus_cus_up, site)
    end if

    call check_co_diffusion_cus_cus_up(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_cus_cus_up, site-(/0, 1/))
    end if

    call check_oxygen_adsorption_bridge_cus_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_cus_left, site-(/-1, 0/))
    end if

    call check_oxygen_adsorption_bridge_cus_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_cus_right, site-(/1, 0/))
    end if

    call check_oxygen_adsorption_cus_cus(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_cus_cus, site)
    end if

    call check_oxygen_adsorption_cus_cus(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_cus_cus, site-(/0, 1/))
    end if

    call check_oxygen_diffusion_bridge_cus_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_cus_left, site-(/-1, 0/))
    end if

    call check_oxygen_diffusion_bridge_cus_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_cus_right, site-(/1, 0/))
    end if

    call check_oxygen_diffusion_cus_cus_down(site-(/0, -1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_cus_cus_down, site-(/0, -1/))
    end if

    call check_oxygen_diffusion_cus_cus_up(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_cus_cus_up, site-(/0, 1/))
    end if

    call ruo2_can_do(reaction_oxygen_bridge_co_cus_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_bridge_co_cus_left, site-(/-1, 0/))
    end if

    call ruo2_can_do(reaction_oxygen_bridge_co_cus_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_bridge_co_cus_right, site-(/1, 0/))
    end if

    call ruo2_can_do(reaction_oxygen_cus_co_cus_down, site-(/0, -1/), can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_cus_co_cus_down, site-(/0, -1/))
    end if

    call ruo2_can_do(reaction_oxygen_cus_co_cus_up, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_cus_co_cus_up, site-(/0, 1/))
    end if


end subroutine take_co_cus

subroutine put_oxygen_bridge(site)

    integer(kind=iint), dimension(2), intent(in) :: site
    logical :: can

    integer(kind=iint) :: nr

    call ruo22nr(site, nr)

    ! lattice updates
    call ruo2_replace_species(site, empty, oxygen)
    ! book keeping updates
    call ruo2_can_do(co_adsorption_bridge, site, can=can)
    if(can)then
        call ruo2_del_proc(co_adsorption_bridge, site)
    end if
    call ruo2_can_do(co_diffusion_bridge_bridge_down, site-(/0, -1/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_bridge_bridge_down, site-(/0, -1/))
    end if
    call ruo2_can_do(co_diffusion_bridge_bridge_up, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_bridge_bridge_up, site-(/0, 1/))
    end if
    call ruo2_can_do(co_diffusion_cus_bridge_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_cus_bridge_left, site-(/-1, 0/))
    end if
    call ruo2_can_do(co_diffusion_cus_bridge_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_cus_bridge_right, site-(/1, 0/))
    end if
    call ruo2_can_do(oxygen_adsorption_bridge_bridge, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_bridge, site)
    end if
    call ruo2_can_do(oxygen_adsorption_bridge_bridge, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_bridge, site-(/0, 1/))
    end if
    call ruo2_can_do(oxygen_adsorption_bridge_cus_left, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_cus_left, site)
    end if
    call ruo2_can_do(oxygen_adsorption_bridge_cus_right, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_cus_right, site)
    end if
    call check_oxygen_desorption_bridge_bridge(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_desorption_bridge_bridge, site)
    end if
    call check_oxygen_desorption_bridge_bridge(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_desorption_bridge_bridge, site-(/0, 1/))
    end if
    call check_oxygen_desorption_bridge_cus_left(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_desorption_bridge_cus_left, site)
    end if
    call check_oxygen_desorption_bridge_cus_right(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_desorption_bridge_cus_right, site)
    end if
    call check_oxygen_diffusion_bridge_bridge_down(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_bridge_down, site)
    end if
    call ruo2_can_do(oxygen_diffusion_bridge_bridge_down, site-(/0, -1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_bridge_down, site-(/0, -1/))
    end if
    call check_oxygen_diffusion_bridge_bridge_up(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_bridge_up, site)
    end if
    call ruo2_can_do(oxygen_diffusion_bridge_bridge_up, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_bridge_up, site-(/0, 1/))
    end if
    call check_oxygen_diffusion_bridge_cus_left(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_cus_left, site)
    end if
    call check_oxygen_diffusion_bridge_cus_right(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_cus_right, site)
    end if
    call ruo2_can_do(oxygen_diffusion_cus_bridge_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_cus_bridge_left, site-(/-1, 0/))
    end if
    call ruo2_can_do(oxygen_diffusion_cus_bridge_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_cus_bridge_right, site-(/1, 0/))
    end if
    call check_reaction_oxygen_bridge_co_bridge_down(site, can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_bridge_co_bridge_down, site)
    end if
    call check_reaction_oxygen_bridge_co_bridge_up(site, can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_bridge_co_bridge_up, site)
    end if
    call check_reaction_oxygen_bridge_co_cus_left(site, can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_bridge_co_cus_left, site)
    end if
    call check_reaction_oxygen_bridge_co_cus_right(site, can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_bridge_co_cus_right, site)
    end if

end subroutine put_oxygen_bridge

subroutine put_oxygen_cus(site)

    integer(kind=iint), dimension(2), intent(in) :: site
    logical :: can

    integer(kind=iint) :: nr

    call ruo22nr(site, nr)

    ! lattice updates
    call ruo2_replace_species(site, empty, oxygen)
    ! book keeping updates
    call ruo2_can_do(co_adsorption_cus, site, can=can)
    if(can)then
        call ruo2_del_proc(co_adsorption_cus, site)
    end if
    call ruo2_can_do(co_diffusion_bridge_cus_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_bridge_cus_left, site-(/-1, 0/))
    end if
    call ruo2_can_do(co_diffusion_bridge_cus_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_bridge_cus_right, site-(/1, 0/))
    end if
    call ruo2_can_do(co_diffusion_cus_cus_down, site-(/0, -1/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_cus_cus_down, site-(/0, -1/))
    end if
    call ruo2_can_do(co_diffusion_cus_cus_up, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(co_diffusion_cus_cus_up, site-(/0, 1/))
    end if
    call ruo2_can_do(oxygen_adsorption_bridge_cus_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_cus_left, site-(/-1, 0/))
    end if
    call ruo2_can_do(oxygen_adsorption_bridge_cus_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_cus_right, site-(/1, 0/))
    end if
    call ruo2_can_do(oxygen_adsorption_cus_cus, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_cus_cus, site)
    end if
    call ruo2_can_do(oxygen_adsorption_cus_cus, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_adsorption_cus_cus, site-(/0, 1/))
    end if
    call check_oxygen_desorption_bridge_cus_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_desorption_bridge_cus_left, site-(/-1, 0/))
    end if
    call check_oxygen_desorption_bridge_cus_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_desorption_bridge_cus_right, site-(/1, 0/))
    end if
    call check_oxygen_desorption_cus_cus(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_desorption_cus_cus, site)
    end if
    call check_oxygen_desorption_cus_cus(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_desorption_cus_cus, site-(/0, 1/))
    end if
    call ruo2_can_do(oxygen_diffusion_bridge_cus_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_cus_left, site-(/-1, 0/))
    end if
    call ruo2_can_do(oxygen_diffusion_bridge_cus_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_cus_right, site-(/1, 0/))
    end if
    call check_oxygen_diffusion_cus_bridge_left(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_cus_bridge_left, site)
    end if
    call check_oxygen_diffusion_cus_bridge_right(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_cus_bridge_right, site)
    end if
    call check_oxygen_diffusion_cus_cus_down(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_cus_cus_down, site)
    end if
    call ruo2_can_do(oxygen_diffusion_cus_cus_down, site-(/0, -1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_cus_cus_down, site-(/0, -1/))
    end if
    call check_oxygen_diffusion_cus_cus_up(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_cus_cus_up, site)
    end if
    call ruo2_can_do(oxygen_diffusion_cus_cus_up, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_cus_cus_up, site-(/0, 1/))
    end if
    call check_reaction_oxygen_cus_co_bridge_left(site, can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_cus_co_bridge_left, site)
    end if
    call check_reaction_oxygen_cus_co_bridge_right(site, can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_cus_co_bridge_right, site)
    end if
    call check_reaction_oxygen_cus_co_cus_down(site, can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_cus_co_cus_down, site)
    end if
    call check_reaction_oxygen_cus_co_cus_up(site, can=can)
    if(can)then
        call ruo2_add_proc(reaction_oxygen_cus_co_cus_up, site)
    end if

end subroutine put_oxygen_cus

subroutine take_oxygen_bridge(site)

    integer(kind=iint), dimension(2), intent(in) :: site
    logical :: can

    integer(kind=iint) :: nr

    call ruo22nr(site, nr)

    ! lattice updates
    call ruo2_replace_species(site, oxygen, empty)
    ! book keeping updates
    call check_co_adsorption_bridge(site, can=can)
    if(can)then
        call ruo2_add_proc(co_adsorption_bridge, site)
    end if

    call check_co_diffusion_bridge_bridge_down(site-(/0, -1/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_bridge_bridge_down, site-(/0, -1/))
    end if

    call check_co_diffusion_bridge_bridge_up(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_bridge_bridge_up, site-(/0, 1/))
    end if

    call check_co_diffusion_cus_bridge_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_cus_bridge_left, site-(/-1, 0/))
    end if

    call check_co_diffusion_cus_bridge_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_cus_bridge_right, site-(/1, 0/))
    end if

    call check_oxygen_adsorption_bridge_bridge(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_bridge, site)
    end if

    call check_oxygen_adsorption_bridge_bridge(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_bridge, site-(/0, 1/))
    end if

    call check_oxygen_adsorption_bridge_cus_left(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_cus_left, site)
    end if

    call check_oxygen_adsorption_bridge_cus_right(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_cus_right, site)
    end if

    call ruo2_can_do(oxygen_desorption_bridge_bridge, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_desorption_bridge_bridge, site)
    end if

    call ruo2_can_do(oxygen_desorption_bridge_bridge, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_desorption_bridge_bridge, site-(/0, 1/))
    end if

    call ruo2_can_do(oxygen_desorption_bridge_cus_left, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_desorption_bridge_cus_left, site)
    end if

    call ruo2_can_do(oxygen_desorption_bridge_cus_right, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_desorption_bridge_cus_right, site)
    end if

    call ruo2_can_do(oxygen_diffusion_bridge_bridge_down, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_bridge_down, site)
    end if

    call check_oxygen_diffusion_bridge_bridge_down(site-(/0, -1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_bridge_down, site-(/0, -1/))
    end if

    call ruo2_can_do(oxygen_diffusion_bridge_bridge_up, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_bridge_up, site)
    end if

    call check_oxygen_diffusion_bridge_bridge_up(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_bridge_up, site-(/0, 1/))
    end if

    call ruo2_can_do(oxygen_diffusion_bridge_cus_left, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_cus_left, site)
    end if

    call ruo2_can_do(oxygen_diffusion_bridge_cus_right, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_cus_right, site)
    end if

    call check_oxygen_diffusion_cus_bridge_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_cus_bridge_left, site-(/-1, 0/))
    end if

    call check_oxygen_diffusion_cus_bridge_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_cus_bridge_right, site-(/1, 0/))
    end if

    call ruo2_can_do(reaction_oxygen_bridge_co_bridge_down, site, can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_bridge_co_bridge_down, site)
    end if

    call ruo2_can_do(reaction_oxygen_bridge_co_bridge_up, site, can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_bridge_co_bridge_up, site)
    end if

    call ruo2_can_do(reaction_oxygen_bridge_co_cus_left, site, can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_bridge_co_cus_left, site)
    end if

    call ruo2_can_do(reaction_oxygen_bridge_co_cus_right, site, can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_bridge_co_cus_right, site)
    end if


end subroutine take_oxygen_bridge

subroutine take_oxygen_cus(site)

    integer(kind=iint), dimension(2), intent(in) :: site
    logical :: can

    integer(kind=iint) :: nr

    call ruo22nr(site, nr)

    ! lattice updates
    call ruo2_replace_species(site, oxygen, empty)
    ! book keeping updates
    call check_co_adsorption_cus(site, can=can)
    if(can)then
        call ruo2_add_proc(co_adsorption_cus, site)
    end if

    call check_co_diffusion_bridge_cus_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_bridge_cus_left, site-(/-1, 0/))
    end if

    call check_co_diffusion_bridge_cus_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_bridge_cus_right, site-(/1, 0/))
    end if

    call check_co_diffusion_cus_cus_down(site-(/0, -1/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_cus_cus_down, site-(/0, -1/))
    end if

    call check_co_diffusion_cus_cus_up(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(co_diffusion_cus_cus_up, site-(/0, 1/))
    end if

    call check_oxygen_adsorption_bridge_cus_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_cus_left, site-(/-1, 0/))
    end if

    call check_oxygen_adsorption_bridge_cus_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_cus_right, site-(/1, 0/))
    end if

    call check_oxygen_adsorption_cus_cus(site, can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_cus_cus, site)
    end if

    call check_oxygen_adsorption_cus_cus(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_adsorption_cus_cus, site-(/0, 1/))
    end if

    call ruo2_can_do(oxygen_desorption_bridge_cus_left, site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_desorption_bridge_cus_left, site-(/-1, 0/))
    end if

    call ruo2_can_do(oxygen_desorption_bridge_cus_right, site-(/1, 0/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_desorption_bridge_cus_right, site-(/1, 0/))
    end if

    call ruo2_can_do(oxygen_desorption_cus_cus, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_desorption_cus_cus, site)
    end if

    call ruo2_can_do(oxygen_desorption_cus_cus, site-(/0, 1/), can=can)
    if(can)then
        call ruo2_del_proc(oxygen_desorption_cus_cus, site-(/0, 1/))
    end if

    call check_oxygen_diffusion_bridge_cus_left(site-(/-1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_cus_left, site-(/-1, 0/))
    end if

    call check_oxygen_diffusion_bridge_cus_right(site-(/1, 0/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_cus_right, site-(/1, 0/))
    end if

    call ruo2_can_do(oxygen_diffusion_cus_bridge_left, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_cus_bridge_left, site)
    end if

    call ruo2_can_do(oxygen_diffusion_cus_bridge_right, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_cus_bridge_right, site)
    end if

    call ruo2_can_do(oxygen_diffusion_cus_cus_down, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_cus_cus_down, site)
    end if

    call check_oxygen_diffusion_cus_cus_down(site-(/0, -1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_cus_cus_down, site-(/0, -1/))
    end if

    call ruo2_can_do(oxygen_diffusion_cus_cus_up, site, can=can)
    if(can)then
        call ruo2_del_proc(oxygen_diffusion_cus_cus_up, site)
    end if

    call check_oxygen_diffusion_cus_cus_up(site-(/0, 1/), can=can)
    if(can)then
        call ruo2_add_proc(oxygen_diffusion_cus_cus_up, site-(/0, 1/))
    end if

    call ruo2_can_do(reaction_oxygen_cus_co_bridge_left, site, can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_cus_co_bridge_left, site)
    end if

    call ruo2_can_do(reaction_oxygen_cus_co_bridge_right, site, can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_cus_co_bridge_right, site)
    end if

    call ruo2_can_do(reaction_oxygen_cus_co_cus_down, site, can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_cus_co_cus_down, site)
    end if

    call ruo2_can_do(reaction_oxygen_cus_co_cus_up, site, can=can)
    if(can)then
        call ruo2_del_proc(reaction_oxygen_cus_co_cus_up, site)
    end if


end subroutine take_oxygen_cus

subroutine touchup_bridge_site(site)
    integer(kind=iint), dimension(2), intent(in) :: site


    logical :: check
    logical :: can


    call ruo2_can_do(co_adsorption_bridge, site, can=can)
    call check_co_adsorption_bridge(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(co_adsorption_bridge, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(co_adsorption_bridge, site)
    end if

    call ruo2_can_do(co_desorption_bridge, site, can=can)
    call check_co_desorption_bridge(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(co_desorption_bridge, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(co_desorption_bridge, site)
    end if

    call ruo2_can_do(co_diffusion_bridge_bridge_down, site, can=can)
    call check_co_diffusion_bridge_bridge_down(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(co_diffusion_bridge_bridge_down, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(co_diffusion_bridge_bridge_down, site)
    end if

    call ruo2_can_do(co_diffusion_bridge_bridge_up, site, can=can)
    call check_co_diffusion_bridge_bridge_up(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(co_diffusion_bridge_bridge_up, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(co_diffusion_bridge_bridge_up, site)
    end if

    call ruo2_can_do(co_diffusion_bridge_cus_left, site, can=can)
    call check_co_diffusion_bridge_cus_left(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(co_diffusion_bridge_cus_left, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(co_diffusion_bridge_cus_left, site)
    end if

    call ruo2_can_do(co_diffusion_bridge_cus_right, site, can=can)
    call check_co_diffusion_bridge_cus_right(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(co_diffusion_bridge_cus_right, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(co_diffusion_bridge_cus_right, site)
    end if

    call ruo2_can_do(oxygen_adsorption_bridge_bridge, site, can=can)
    call check_oxygen_adsorption_bridge_bridge(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_bridge, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_bridge, site)
    end if

    call ruo2_can_do(oxygen_adsorption_bridge_cus_left, site, can=can)
    call check_oxygen_adsorption_bridge_cus_left(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_cus_left, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_cus_left, site)
    end if

    call ruo2_can_do(oxygen_adsorption_bridge_cus_right, site, can=can)
    call check_oxygen_adsorption_bridge_cus_right(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_adsorption_bridge_cus_right, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_adsorption_bridge_cus_right, site)
    end if

    call ruo2_can_do(oxygen_desorption_bridge_bridge, site, can=can)
    call check_oxygen_desorption_bridge_bridge(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_desorption_bridge_bridge, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_desorption_bridge_bridge, site)
    end if

    call ruo2_can_do(oxygen_desorption_bridge_cus_left, site, can=can)
    call check_oxygen_desorption_bridge_cus_left(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_desorption_bridge_cus_left, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_desorption_bridge_cus_left, site)
    end if

    call ruo2_can_do(oxygen_desorption_bridge_cus_right, site, can=can)
    call check_oxygen_desorption_bridge_cus_right(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_desorption_bridge_cus_right, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_desorption_bridge_cus_right, site)
    end if

    call ruo2_can_do(oxygen_diffusion_bridge_bridge_down, site, can=can)
    call check_oxygen_diffusion_bridge_bridge_down(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_bridge_down, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_bridge_down, site)
    end if

    call ruo2_can_do(oxygen_diffusion_bridge_bridge_up, site, can=can)
    call check_oxygen_diffusion_bridge_bridge_up(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_bridge_up, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_bridge_up, site)
    end if

    call ruo2_can_do(oxygen_diffusion_bridge_cus_left, site, can=can)
    call check_oxygen_diffusion_bridge_cus_left(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_cus_left, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_cus_left, site)
    end if

    call ruo2_can_do(oxygen_diffusion_bridge_cus_right, site, can=can)
    call check_oxygen_diffusion_bridge_cus_right(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_diffusion_bridge_cus_right, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_diffusion_bridge_cus_right, site)
    end if

    call ruo2_can_do(reaction_oxygen_bridge_co_bridge_down, site, can=can)
    call check_reaction_oxygen_bridge_co_bridge_down(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(reaction_oxygen_bridge_co_bridge_down, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(reaction_oxygen_bridge_co_bridge_down, site)
    end if

    call ruo2_can_do(reaction_oxygen_bridge_co_bridge_up, site, can=can)
    call check_reaction_oxygen_bridge_co_bridge_up(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(reaction_oxygen_bridge_co_bridge_up, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(reaction_oxygen_bridge_co_bridge_up, site)
    end if

    call ruo2_can_do(reaction_oxygen_bridge_co_cus_left, site, can=can)
    call check_reaction_oxygen_bridge_co_cus_left(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(reaction_oxygen_bridge_co_cus_left, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(reaction_oxygen_bridge_co_cus_left, site)
    end if

    call ruo2_can_do(reaction_oxygen_bridge_co_cus_right, site, can=can)
    call check_reaction_oxygen_bridge_co_cus_right(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(reaction_oxygen_bridge_co_cus_right, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(reaction_oxygen_bridge_co_cus_right, site)
    end if

end subroutine touchup_bridge_site


subroutine touchup_cus_site(site)
    integer(kind=iint), dimension(2), intent(in) :: site


    logical :: check
    logical :: can


    call ruo2_can_do(co_adsorption_cus, site, can=can)
    call check_co_adsorption_cus(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(co_adsorption_cus, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(co_adsorption_cus, site)
    end if

    call ruo2_can_do(co_desorption_cus, site, can=can)
    call check_co_desorption_cus(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(co_desorption_cus, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(co_desorption_cus, site)
    end if

    call ruo2_can_do(co_diffusion_cus_bridge_left, site, can=can)
    call check_co_diffusion_cus_bridge_left(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(co_diffusion_cus_bridge_left, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(co_diffusion_cus_bridge_left, site)
    end if

    call ruo2_can_do(co_diffusion_cus_bridge_right, site, can=can)
    call check_co_diffusion_cus_bridge_right(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(co_diffusion_cus_bridge_right, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(co_diffusion_cus_bridge_right, site)
    end if

    call ruo2_can_do(co_diffusion_cus_cus_down, site, can=can)
    call check_co_diffusion_cus_cus_down(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(co_diffusion_cus_cus_down, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(co_diffusion_cus_cus_down, site)
    end if

    call ruo2_can_do(co_diffusion_cus_cus_up, site, can=can)
    call check_co_diffusion_cus_cus_up(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(co_diffusion_cus_cus_up, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(co_diffusion_cus_cus_up, site)
    end if

    call ruo2_can_do(oxygen_adsorption_cus_cus, site, can=can)
    call check_oxygen_adsorption_cus_cus(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_adsorption_cus_cus, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_adsorption_cus_cus, site)
    end if

    call ruo2_can_do(oxygen_desorption_cus_cus, site, can=can)
    call check_oxygen_desorption_cus_cus(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_desorption_cus_cus, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_desorption_cus_cus, site)
    end if

    call ruo2_can_do(oxygen_diffusion_cus_bridge_left, site, can=can)
    call check_oxygen_diffusion_cus_bridge_left(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_diffusion_cus_bridge_left, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_diffusion_cus_bridge_left, site)
    end if

    call ruo2_can_do(oxygen_diffusion_cus_bridge_right, site, can=can)
    call check_oxygen_diffusion_cus_bridge_right(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_diffusion_cus_bridge_right, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_diffusion_cus_bridge_right, site)
    end if

    call ruo2_can_do(oxygen_diffusion_cus_cus_down, site, can=can)
    call check_oxygen_diffusion_cus_cus_down(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_diffusion_cus_cus_down, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_diffusion_cus_cus_down, site)
    end if

    call ruo2_can_do(oxygen_diffusion_cus_cus_up, site, can=can)
    call check_oxygen_diffusion_cus_cus_up(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(oxygen_diffusion_cus_cus_up, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(oxygen_diffusion_cus_cus_up, site)
    end if

    call ruo2_can_do(reaction_oxygen_cus_co_bridge_left, site, can=can)
    call check_reaction_oxygen_cus_co_bridge_left(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(reaction_oxygen_cus_co_bridge_left, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(reaction_oxygen_cus_co_bridge_left, site)
    end if

    call ruo2_can_do(reaction_oxygen_cus_co_bridge_right, site, can=can)
    call check_reaction_oxygen_cus_co_bridge_right(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(reaction_oxygen_cus_co_bridge_right, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(reaction_oxygen_cus_co_bridge_right, site)
    end if

    call ruo2_can_do(reaction_oxygen_cus_co_cus_down, site, can=can)
    call check_reaction_oxygen_cus_co_cus_down(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(reaction_oxygen_cus_co_cus_down, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(reaction_oxygen_cus_co_cus_down, site)
    end if

    call ruo2_can_do(reaction_oxygen_cus_co_cus_up, site, can=can)
    call check_reaction_oxygen_cus_co_cus_up(site, check)
    if(check .and. .not. can)then
        call ruo2_add_proc(reaction_oxygen_cus_co_cus_up, site)
    else if(.not. check .and. can)then
        call ruo2_del_proc(reaction_oxygen_cus_co_cus_up, site)
    end if

end subroutine touchup_cus_site


subroutine check_co_adsorption_bridge(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_co_adsorption_bridge


subroutine check_co_adsorption_cus(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_co_adsorption_cus


subroutine check_co_desorption_bridge(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.co)then
        can = .false.; return
    end if

end subroutine check_co_desorption_bridge


subroutine check_co_desorption_cus(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.co)then
        can = .false.; return
    end if

end subroutine check_co_desorption_cus


subroutine check_co_diffusion_bridge_bridge_down(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.co)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, -1/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_co_diffusion_bridge_bridge_down


subroutine check_co_diffusion_bridge_bridge_up(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.co)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, 1/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_co_diffusion_bridge_bridge_up


subroutine check_co_diffusion_bridge_cus_left(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.co)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/-1, 0/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_co_diffusion_bridge_cus_left


subroutine check_co_diffusion_bridge_cus_right(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.co)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/1, 0/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_co_diffusion_bridge_cus_right


subroutine check_co_diffusion_cus_bridge_left(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.co)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/-1, 0/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_co_diffusion_cus_bridge_left


subroutine check_co_diffusion_cus_bridge_right(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.co)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/1, 0/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_co_diffusion_cus_bridge_right


subroutine check_co_diffusion_cus_cus_down(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.co)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, -1/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_co_diffusion_cus_cus_down


subroutine check_co_diffusion_cus_cus_up(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.co)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, 1/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_co_diffusion_cus_cus_up


subroutine check_oxygen_adsorption_bridge_bridge(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.empty)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, 1/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_oxygen_adsorption_bridge_bridge


subroutine check_oxygen_adsorption_bridge_cus_left(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.empty)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/-1, 0/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_oxygen_adsorption_bridge_cus_left


subroutine check_oxygen_adsorption_bridge_cus_right(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.empty)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/1, 0/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_oxygen_adsorption_bridge_cus_right


subroutine check_oxygen_adsorption_cus_cus(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.empty)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, 1/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_oxygen_adsorption_cus_cus


subroutine check_oxygen_desorption_bridge_bridge(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, 1/), species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

end subroutine check_oxygen_desorption_bridge_bridge


subroutine check_oxygen_desorption_bridge_cus_left(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/-1, 0/), species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

end subroutine check_oxygen_desorption_bridge_cus_left


subroutine check_oxygen_desorption_bridge_cus_right(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/1, 0/), species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

end subroutine check_oxygen_desorption_bridge_cus_right


subroutine check_oxygen_desorption_cus_cus(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, 1/), species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

end subroutine check_oxygen_desorption_cus_cus


subroutine check_oxygen_diffusion_bridge_bridge_down(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, -1/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_oxygen_diffusion_bridge_bridge_down


subroutine check_oxygen_diffusion_bridge_bridge_up(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, 1/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_oxygen_diffusion_bridge_bridge_up


subroutine check_oxygen_diffusion_bridge_cus_left(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/-1, 0/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_oxygen_diffusion_bridge_cus_left


subroutine check_oxygen_diffusion_bridge_cus_right(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/1, 0/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_oxygen_diffusion_bridge_cus_right


subroutine check_oxygen_diffusion_cus_bridge_left(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/-1, 0/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_oxygen_diffusion_cus_bridge_left


subroutine check_oxygen_diffusion_cus_bridge_right(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/1, 0/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_oxygen_diffusion_cus_bridge_right


subroutine check_oxygen_diffusion_cus_cus_down(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, -1/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_oxygen_diffusion_cus_cus_down


subroutine check_oxygen_diffusion_cus_cus_up(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, 1/), species)
    if(species.ne.empty)then
        can = .false.; return
    end if

end subroutine check_oxygen_diffusion_cus_cus_up


subroutine check_reaction_oxygen_bridge_co_bridge_down(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, -1/), species)
    if(species.ne.co)then
        can = .false.; return
    end if

end subroutine check_reaction_oxygen_bridge_co_bridge_down


subroutine check_reaction_oxygen_bridge_co_bridge_up(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, 1/), species)
    if(species.ne.co)then
        can = .false.; return
    end if

end subroutine check_reaction_oxygen_bridge_co_bridge_up


subroutine check_reaction_oxygen_bridge_co_cus_left(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/-1, 0/), species)
    if(species.ne.co)then
        can = .false.; return
    end if

end subroutine check_reaction_oxygen_bridge_co_cus_left


subroutine check_reaction_oxygen_bridge_co_cus_right(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/1, 0/), species)
    if(species.ne.co)then
        can = .false.; return
    end if

end subroutine check_reaction_oxygen_bridge_co_cus_right


subroutine check_reaction_oxygen_cus_co_bridge_left(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/-1, 0/), species)
    if(species.ne.co)then
        can = .false.; return
    end if

end subroutine check_reaction_oxygen_cus_co_bridge_left


subroutine check_reaction_oxygen_cus_co_bridge_right(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/1, 0/), species)
    if(species.ne.co)then
        can = .false.; return
    end if

end subroutine check_reaction_oxygen_cus_co_bridge_right


subroutine check_reaction_oxygen_cus_co_cus_down(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, -1/), species)
    if(species.ne.co)then
        can = .false.; return
    end if

end subroutine check_reaction_oxygen_cus_co_cus_down


subroutine check_reaction_oxygen_cus_co_cus_up(site, can)
    !-----------------I/O variables-------------------
    integer(kind=iint), intent(in), dimension(2) :: site
    logical, intent(out) :: can
    !-----------------Internal variables-------------------
    integer(kind=iint) :: species

    can = .true.


    call ruo2_get_species(site, species)
    if(species.ne.oxygen)then
        can = .false.; return
    end if

    call ruo2_get_species(site+(/0, 1/), species)
    if(species.ne.co)then
        can = .false.; return
    end if

end subroutine check_reaction_oxygen_cus_co_cus_up


end module proclist
