!  This file was generated by kMOS (kMC modelling on steroids)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2012.
!  The model was written by Max J. Hoffmann.

!  This file is part of kmos.
!
!  kmos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
!****h* kmos/proclist
! FUNCTION
!    Implements the kMC process list.
!
!******


module proclist
use kind_values
use base, only: &
    update_accum_rate, &
    update_integ_rate, &
    determine_procsite, &
    update_clocks, &
    avail_sites, &
    null_species, &
    increment_procstat

use lattice, only: &
    ruo2, &
    ruo2_bridge, &
    ruo2_cus, &
    allocate_system, &
    nr2lattice, &
    lattice2nr, &
    add_proc, &
    can_do, &
    set_rate_const, &
    replace_species, &
    del_proc, &
    reset_site, &
    system_size, &
    spuck, &
    get_species


implicit none



 ! Species constants



integer(kind=iint), parameter, public :: nr_of_species = 3
integer(kind=iint), parameter, public :: co = 0
integer(kind=iint), parameter, public :: empty = 1
integer(kind=iint), parameter, public :: oxygen = 2
integer(kind=iint), public :: default_species = empty


! Process constants

integer(kind=iint), parameter, public :: co_adsorption_bridge = 1
integer(kind=iint), parameter, public :: co_adsorption_cus = 2
integer(kind=iint), parameter, public :: co_desorption_bridge = 3
integer(kind=iint), parameter, public :: co_desorption_cus = 4
integer(kind=iint), parameter, public :: co_diffusion_bridge_bridge_down = 5
integer(kind=iint), parameter, public :: co_diffusion_bridge_bridge_up = 6
integer(kind=iint), parameter, public :: co_diffusion_bridge_cus_left = 7
integer(kind=iint), parameter, public :: co_diffusion_bridge_cus_right = 8
integer(kind=iint), parameter, public :: co_diffusion_cus_bridge_left = 9
integer(kind=iint), parameter, public :: co_diffusion_cus_bridge_right = 10
integer(kind=iint), parameter, public :: co_diffusion_cus_cus_down = 11
integer(kind=iint), parameter, public :: co_diffusion_cus_cus_up = 12
integer(kind=iint), parameter, public :: oxygen_adsorption_bridge_bridge = 13
integer(kind=iint), parameter, public :: oxygen_adsorption_bridge_cus_left = 14
integer(kind=iint), parameter, public :: oxygen_adsorption_bridge_cus_right = 15
integer(kind=iint), parameter, public :: oxygen_adsorption_cus_cus = 16
integer(kind=iint), parameter, public :: oxygen_desorption_bridge_bridge = 17
integer(kind=iint), parameter, public :: oxygen_desorption_bridge_cus_left = 18
integer(kind=iint), parameter, public :: oxygen_desorption_bridge_cus_right = 19
integer(kind=iint), parameter, public :: oxygen_desorption_cus_cus = 20
integer(kind=iint), parameter, public :: oxygen_diffusion_bridge_bridge_down = 21
integer(kind=iint), parameter, public :: oxygen_diffusion_bridge_bridge_up = 22
integer(kind=iint), parameter, public :: oxygen_diffusion_bridge_cus_left = 23
integer(kind=iint), parameter, public :: oxygen_diffusion_bridge_cus_right = 24
integer(kind=iint), parameter, public :: oxygen_diffusion_cus_bridge_left = 25
integer(kind=iint), parameter, public :: oxygen_diffusion_cus_bridge_right = 26
integer(kind=iint), parameter, public :: oxygen_diffusion_cus_cus_down = 27
integer(kind=iint), parameter, public :: oxygen_diffusion_cus_cus_up = 28
integer(kind=iint), parameter, public :: reaction_oxygen_bridge_co_bridge_down = 29
integer(kind=iint), parameter, public :: reaction_oxygen_bridge_co_bridge_up = 30
integer(kind=iint), parameter, public :: reaction_oxygen_bridge_co_cus_left = 31
integer(kind=iint), parameter, public :: reaction_oxygen_bridge_co_cus_right = 32
integer(kind=iint), parameter, public :: reaction_oxygen_cus_co_bridge_left = 33
integer(kind=iint), parameter, public :: reaction_oxygen_cus_co_bridge_right = 34
integer(kind=iint), parameter, public :: reaction_oxygen_cus_co_cus_down = 35
integer(kind=iint), parameter, public :: reaction_oxygen_cus_co_cus_up = 36


integer(kind=iint), parameter, public :: representation_length = 0
integer(kind=iint), public :: seed_size = 12
integer(kind=iint), public :: seed ! random seed
integer(kind=iint), public, dimension(:), allocatable :: seed_arr ! random seed


integer(kind=iint), parameter, public :: nr_of_proc = 36


contains

subroutine do_kmc_steps(n)

!****f* proclist/do_kmc_steps
! FUNCTION
!    Performs ``n`` kMC step.
!    If one has to run many steps without evaluation
!    do_kmc_steps might perform a little better.
!      first update clock
!      then configuration sampling step
!      last execute process
!
! ARGUMENTS
!
!    ``n`` : Number of steps to run
!******
    integer(kind=iint), intent(in) :: n

    real(kind=rsingle) :: ran_proc, ran_time, ran_site
    integer(kind=iint) :: nr_site, proc_nr, i

    do i = 1, n
    call random_number(ran_time)
    call random_number(ran_proc)
    call random_number(ran_site)
    call update_accum_rate
    call update_clocks(ran_time)

    call update_integ_rate
    call determine_procsite(ran_proc, ran_time, proc_nr, nr_site)
    call run_proc_nr(proc_nr, nr_site)
    enddo

end subroutine do_kmc_steps

subroutine do_kmc_step()

!****f* proclist/do_kmc_step
! FUNCTION
!    Performs exactly one kMC step.
!      first update clock
!      then configuration sampling step
!      last execute process
!
! ARGUMENTS
!
!    ``none``
!******
    real(kind=rsingle) :: ran_proc, ran_time, ran_site
    integer(kind=iint) :: nr_site, proc_nr

    call random_number(ran_time)
    call random_number(ran_proc)
    call random_number(ran_site)
    call update_accum_rate
    call update_clocks(ran_time)

    call update_integ_rate
    call determine_procsite(ran_proc, ran_time, proc_nr, nr_site)
    call run_proc_nr(proc_nr, nr_site)
end subroutine do_kmc_step

subroutine get_next_kmc_step(proc_nr, nr_site)

!****f* proclist/get_kmc_step
! FUNCTION
!    Determines next step without executing it.
!
! ARGUMENTS
!
!    ``none``
!******
    real(kind=rsingle) :: ran_proc, ran_time, ran_site
    integer(kind=iint), intent(out) :: nr_site, proc_nr

    call random_number(ran_time)
    call random_number(ran_proc)
    call random_number(ran_site)
    call update_accum_rate
    call determine_procsite(ran_proc, ran_time, proc_nr, nr_site)

end subroutine get_next_kmc_step

subroutine get_occupation(occupation)

!****f* proclist/get_occupation
! FUNCTION
!    Evaluate current lattice configuration and returns
!    the normalized occupation as matrix. Different species
!    run along the first axis and different sites run
!    along the second.
!
! ARGUMENTS
!
!    ``none``
!******
    ! nr_of_species = 3, spuck = 2
    real(kind=rdouble), dimension(0:2, 1:2), intent(out) :: occupation

    integer(kind=iint) :: i, j, k, nr, species

    occupation = 0

    do k = 0, system_size(3)-1
        do j = 0, system_size(2)-1
            do i = 0, system_size(1)-1
                do nr = 1, spuck
                    ! shift position by 1, so it can be accessed
                    ! more straightforwardly from f2py interface
                    species = get_species((/i,j,k,nr/))
                    if(species.ne.null_species) then
                    occupation(species, nr) = &
                        occupation(species, nr) + 1
                    endif
                end do
            end do
        end do
    end do

    occupation = occupation/real(system_size(1)*system_size(2)*system_size(3))
end subroutine get_occupation

subroutine init(input_system_size, system_name, layer, no_banner)

!****f* proclist/init
! FUNCTION
!     Allocates the system and initializes all sites in the given
!     layer.
!
! ARGUMENTS
!
!    * ``input_system_size`` number of unit cell per axis.
!    * ``system_name`` identifier for reload file.
!    * ``layer`` initial layer.
!    * ``no_banner`` [optional] if True no copyright is issued.
!******
    integer(kind=iint), intent(in) :: layer
    integer(kind=iint), dimension(2), intent(in) :: input_system_size

    character(len=400), intent(in) :: system_name

    logical, optional, intent(in) :: no_banner

    if (.not. no_banner) then
        print *, "+------------------------------------------------------------+"
        print *, "|                                                            |"
        print *, "| This kMC Model 'my_model' was written by                   |"
        print *, "|                                                            |"
        print *, "|           Max J. Hoffmann (mjhoffmann@gmail.com)           |"
        print *, "|                                                            |"
        print *, "| and implemented with the help of kmos,                     |"
        print *, "| which is distributed under GNU/GPL Version 3               |"
        print *, "| (C) Max J. Hoffmann mjhoffmann@gmail.com                   |"
        print *, "|                                                            |"
        print *, "| kmos is distributed in the hope that it will be useful     |"
        print *, "| but WIHTOUT ANY WARRANTY; without even the implied         |"
        print *, "| waranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR     |"
        print *, "| PURPOSE. See the GNU General Public License for more       |"
        print *, "| details.                                                   |"
        print *, "|                                                            |"
        print *, "| I appreciate, but do not require, attribution.             |"
        print *, "| An attribution usually includes the program name           |"
        print *, "| author, and URL. For example:                              |"
        print *, "| kmos by Max J. Hoffmann, (http://mhoffman.github.com/kmos) |"
        print *, "|                                                            |"
        print *, "+------------------------------------------------------------+"
        print *, ""
        print *, ""
    endif
    call allocate_system(nr_of_proc, input_system_size, system_name)
    call initialize_state(layer)
end subroutine init

subroutine initialize_state(layer)

!****f* proclist/initialize_state
! FUNCTION
!    Initialize all sites and book-keeping array
!    for the given layer.
!
! ARGUMENTS
!
!    * ``layer`` integer representing layer
!******
    integer(kind=iint), intent(in) :: layer

    integer(kind=iint) :: i, j, k, nr
    ! initialize random number generator
    allocate(seed_arr(seed_size))
    seed_arr = seed
    call random_seed(seed_size)
    call random_seed(put=seed_arr)
    deallocate(seed_arr)
    do k = 0, system_size(3)-1
        do j = 0, system_size(2)-1
            do i = 0, system_size(1)-1
                do nr = 1, spuck
                    call reset_site((/i, j, k, nr/), null_species)
                end do
                select case(layer)
                case (ruo2)
                    call replace_species((/i, j, k, ruo2_bridge/), null_species, default_species)
                    call replace_species((/i, j, k, ruo2_cus/), null_species, default_species)
                end select
            end do
        end do
    end do

    do k = 0, system_size(3)-1
        do j = 0, system_size(2)-1
            do i = 0, system_size(1)-1
                select case(layer)
                case(ruo2)
                    call touchup_ruo2_bridge((/i, j, k, ruo2_bridge/))
                    call touchup_ruo2_cus((/i, j, k, ruo2_cus/))
                end select
            end do
        end do
    end do


end subroutine initialize_state

subroutine run_proc_nr(proc, nr_site)

!****f* proclist/run_proc_nr
! FUNCTION
!    Runs process ``proc`` on site ``nr_site``.
!
! ARGUMENTS
!
!    * ``proc`` integer representing the process number
!    * ``nr_site``  integer representing the site
!******
    integer(kind=iint), intent(in) :: proc
    integer(kind=iint), intent(in) :: nr_site

    integer(kind=iint), dimension(4) :: lsite

    call increment_procstat(proc)

    ! lsite = lattice_site, (vs. scalar site)
    lsite = nr2lattice(nr_site, :)

    select case(proc)
    case(co_adsorption_bridge)
        call put_co_ruo2_bridge(lsite)

    case(co_adsorption_cus)
        call put_co_ruo2_cus(lsite)

    case(co_desorption_bridge)
        call take_co_ruo2_bridge(lsite)

    case(co_desorption_cus)
        call take_co_ruo2_cus(lsite)

    case(co_diffusion_bridge_bridge_down)
        call put_co_ruo2_bridge(lsite)
        call take_co_ruo2_bridge(lsite + (/0, 1, 0, 0/))

    case(co_diffusion_bridge_bridge_up)
        call put_co_ruo2_bridge(lsite + (/0, 1, 0, 0/))
        call take_co_ruo2_bridge(lsite)

    case(co_diffusion_bridge_cus_left)
        call take_co_ruo2_bridge(lsite)
        call put_co_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))

    case(co_diffusion_bridge_cus_right)
        call take_co_ruo2_bridge(lsite)
        call put_co_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))

    case(co_diffusion_cus_bridge_left)
        call put_co_ruo2_bridge(lsite)
        call take_co_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))

    case(co_diffusion_cus_bridge_right)
        call take_co_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))
        call put_co_ruo2_bridge(lsite)

    case(co_diffusion_cus_cus_down)
        call put_co_ruo2_cus(lsite)
        call take_co_ruo2_cus(lsite + (/0, 1, 0, 0/))

    case(co_diffusion_cus_cus_up)
        call take_co_ruo2_cus(lsite)
        call put_co_ruo2_cus(lsite + (/0, 1, 0, 0/))

    case(oxygen_adsorption_bridge_bridge)
        call put_oxygen_ruo2_bridge(lsite + (/0, 1, 0, 0/))
        call put_oxygen_ruo2_bridge(lsite)

    case(oxygen_adsorption_bridge_cus_left)
        call put_oxygen_ruo2_bridge(lsite)
        call put_oxygen_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))

    case(oxygen_adsorption_bridge_cus_right)
        call put_oxygen_ruo2_bridge(lsite)
        call put_oxygen_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))

    case(oxygen_adsorption_cus_cus)
        call put_oxygen_ruo2_cus(lsite)
        call put_oxygen_ruo2_cus(lsite + (/0, 1, 0, 0/))

    case(oxygen_desorption_bridge_bridge)
        call take_oxygen_ruo2_bridge(lsite + (/0, 1, 0, 0/))
        call take_oxygen_ruo2_bridge(lsite)

    case(oxygen_desorption_bridge_cus_left)
        call take_oxygen_ruo2_bridge(lsite)
        call take_oxygen_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))

    case(oxygen_desorption_bridge_cus_right)
        call take_oxygen_ruo2_bridge(lsite)
        call take_oxygen_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))

    case(oxygen_desorption_cus_cus)
        call take_oxygen_ruo2_cus(lsite + (/0, 1, 0, 0/))
        call take_oxygen_ruo2_cus(lsite)

    case(oxygen_diffusion_bridge_bridge_down)
        call put_oxygen_ruo2_bridge(lsite)
        call take_oxygen_ruo2_bridge(lsite + (/0, 1, 0, 0/))

    case(oxygen_diffusion_bridge_bridge_up)
        call take_oxygen_ruo2_bridge(lsite)
        call put_oxygen_ruo2_bridge(lsite + (/0, 1, 0, 0/))

    case(oxygen_diffusion_bridge_cus_left)
        call take_oxygen_ruo2_bridge(lsite)
        call put_oxygen_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))

    case(oxygen_diffusion_bridge_cus_right)
        call take_oxygen_ruo2_bridge(lsite)
        call put_oxygen_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))

    case(oxygen_diffusion_cus_bridge_left)
        call put_oxygen_ruo2_bridge(lsite)
        call take_oxygen_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))

    case(oxygen_diffusion_cus_bridge_right)
        call take_oxygen_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))
        call put_oxygen_ruo2_bridge(lsite)

    case(oxygen_diffusion_cus_cus_down)
        call put_oxygen_ruo2_cus(lsite)
        call take_oxygen_ruo2_cus(lsite + (/0, 1, 0, 0/))

    case(oxygen_diffusion_cus_cus_up)
        call put_oxygen_ruo2_cus(lsite + (/0, 1, 0, 0/))
        call take_oxygen_ruo2_cus(lsite)

    case(reaction_oxygen_bridge_co_bridge_down)
        call take_oxygen_ruo2_bridge(lsite + (/0, 1, 0, 0/))
        call take_co_ruo2_bridge(lsite)

    case(reaction_oxygen_bridge_co_bridge_up)
        call take_co_ruo2_bridge(lsite + (/0, 1, 0, 0/))
        call take_oxygen_ruo2_bridge(lsite)

    case(reaction_oxygen_bridge_co_cus_left)
        call take_oxygen_ruo2_bridge(lsite)
        call take_co_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))

    case(reaction_oxygen_bridge_co_cus_right)
        call take_oxygen_ruo2_bridge(lsite)
        call take_co_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))

    case(reaction_oxygen_cus_co_bridge_left)
        call take_oxygen_ruo2_cus(lsite + (/0, 0, 0, ruo2_cus - ruo2_bridge/))
        call take_co_ruo2_bridge(lsite)

    case(reaction_oxygen_cus_co_bridge_right)
        call take_oxygen_ruo2_cus(lsite + (/-1, 0, 0, ruo2_cus - ruo2_bridge/))
        call take_co_ruo2_bridge(lsite)

    case(reaction_oxygen_cus_co_cus_down)
        call take_oxygen_ruo2_cus(lsite + (/0, 1, 0, 0/))
        call take_co_ruo2_cus(lsite)

    case(reaction_oxygen_cus_co_cus_up)
        call take_oxygen_ruo2_cus(lsite)
        call take_co_ruo2_cus(lsite + (/0, 1, 0, 0/))

    end select

end subroutine run_proc_nr

subroutine put_co_ruo2_bridge(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, empty, co)

    ! disable affected processes
    if(avail_sites(co_adsorption_bridge, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_adsorption_bridge, site)
    endif

    if(avail_sites(co_diffusion_bridge_bridge_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_diffusion_bridge_bridge_down, site)
    endif

    if(avail_sites(co_diffusion_bridge_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(co_diffusion_bridge_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(co_diffusion_cus_bridge_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_diffusion_cus_bridge_left, site)
    endif

    if(avail_sites(co_diffusion_cus_bridge_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_diffusion_cus_bridge_right, site)
    endif

    if(avail_sites(oxygen_adsorption_bridge_bridge, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_adsorption_bridge_bridge, site)
    endif

    if(avail_sites(oxygen_adsorption_bridge_bridge, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(oxygen_adsorption_bridge_bridge, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(oxygen_adsorption_bridge_cus_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_adsorption_bridge_cus_left, site)
    endif

    if(avail_sites(oxygen_adsorption_bridge_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_adsorption_bridge_cus_right, site)
    endif

    if(avail_sites(oxygen_diffusion_bridge_bridge_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_diffusion_bridge_bridge_down, site)
    endif

    if(avail_sites(oxygen_diffusion_bridge_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(oxygen_diffusion_bridge_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(oxygen_diffusion_cus_bridge_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_diffusion_cus_bridge_left, site)
    endif

    if(avail_sites(oxygen_diffusion_cus_bridge_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_diffusion_cus_bridge_right, site)
    endif

    ! enable affected processes
    call add_proc(co_desorption_bridge, site)
    select case(get_species(site + (/0, -1, 0, 0/)))
    case(oxygen)
        call add_proc(reaction_oxygen_bridge_co_bridge_up, site + (/0, -1, 0, 0/))
    case(empty)
        call add_proc(co_diffusion_bridge_bridge_down, site + (/0, -1, 0, 0/))
    end select

    select case(get_species(site + (/0, 1, 0, 0/)))
    case(oxygen)
        call add_proc(reaction_oxygen_bridge_co_bridge_down, site)
    case(empty)
        call add_proc(co_diffusion_bridge_bridge_up, site)
    end select

    select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(oxygen)
        call add_proc(reaction_oxygen_cus_co_bridge_right, site)
    case(empty)
        call add_proc(co_diffusion_bridge_cus_left, site)
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(oxygen)
        call add_proc(reaction_oxygen_cus_co_bridge_left, site)
    case(empty)
        call add_proc(co_diffusion_bridge_cus_right, site)
    end select


end subroutine put_co_ruo2_bridge

subroutine take_co_ruo2_bridge(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, co, empty)

    ! disable affected processes
    if(avail_sites(co_desorption_bridge, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_desorption_bridge, site)
    endif

    if(avail_sites(co_diffusion_bridge_bridge_down, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(co_diffusion_bridge_bridge_down, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(co_diffusion_bridge_bridge_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_diffusion_bridge_bridge_up, site)
    endif

    if(avail_sites(co_diffusion_bridge_cus_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_diffusion_bridge_cus_left, site)
    endif

    if(avail_sites(co_diffusion_bridge_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_diffusion_bridge_cus_right, site)
    endif

    if(avail_sites(reaction_oxygen_bridge_co_bridge_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(reaction_oxygen_bridge_co_bridge_down, site)
    endif

    if(avail_sites(reaction_oxygen_bridge_co_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(reaction_oxygen_bridge_co_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(reaction_oxygen_cus_co_bridge_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(reaction_oxygen_cus_co_bridge_left, site)
    endif

    if(avail_sites(reaction_oxygen_cus_co_bridge_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(reaction_oxygen_cus_co_bridge_right, site)
    endif

    ! enable affected processes
    call add_proc(co_adsorption_bridge, site)
    select case(get_species(site + (/0, 1, 0, 0/)))
    case(co)
        call add_proc(co_diffusion_bridge_bridge_down, site)
    case(oxygen)
        call add_proc(oxygen_diffusion_bridge_bridge_down, site)
    case(empty)
        call add_proc(oxygen_adsorption_bridge_bridge, site)
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(co)
        call add_proc(co_diffusion_bridge_bridge_up, site + (/0, -1, 0, 0/))
    case(oxygen)
        call add_proc(oxygen_diffusion_bridge_bridge_up, site + (/0, -1, 0, 0/))
    case(empty)
        call add_proc(oxygen_adsorption_bridge_bridge, site + (/0, -1, 0, 0/))
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(co)
        call add_proc(co_diffusion_cus_bridge_left, site)
    case(oxygen)
        call add_proc(oxygen_diffusion_cus_bridge_left, site)
    case(empty)
        call add_proc(oxygen_adsorption_bridge_cus_right, site)
    end select

    select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(co)
        call add_proc(co_diffusion_cus_bridge_right, site)
    case(oxygen)
        call add_proc(oxygen_diffusion_cus_bridge_right, site)
    case(empty)
        call add_proc(oxygen_adsorption_bridge_cus_left, site)
    end select


end subroutine take_co_ruo2_bridge

subroutine put_co_ruo2_cus(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, empty, co)

    ! disable affected processes
    if(avail_sites(co_adsorption_cus, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_adsorption_cus, site)
    endif

    if(avail_sites(co_diffusion_bridge_cus_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(co_diffusion_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(co_diffusion_bridge_cus_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(co_diffusion_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(co_diffusion_cus_cus_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_diffusion_cus_cus_down, site)
    endif

    if(avail_sites(co_diffusion_cus_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(co_diffusion_cus_cus_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(oxygen_adsorption_bridge_cus_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(oxygen_adsorption_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(oxygen_adsorption_bridge_cus_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(oxygen_adsorption_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(oxygen_adsorption_cus_cus, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_adsorption_cus_cus, site)
    endif

    if(avail_sites(oxygen_adsorption_cus_cus, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(oxygen_adsorption_cus_cus, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(oxygen_diffusion_bridge_cus_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(oxygen_diffusion_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(oxygen_diffusion_bridge_cus_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(oxygen_diffusion_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(oxygen_diffusion_cus_cus_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_diffusion_cus_cus_down, site)
    endif

    if(avail_sites(oxygen_diffusion_cus_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(oxygen_diffusion_cus_cus_up, site + (/0, -1, 0, 0/))
    endif

    ! enable affected processes
    call add_proc(co_desorption_cus, site)
    select case(get_species(site + (/0, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(oxygen)
        call add_proc(reaction_oxygen_bridge_co_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(empty)
        call add_proc(co_diffusion_cus_bridge_left, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/1, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(oxygen)
        call add_proc(reaction_oxygen_bridge_co_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(empty)
        call add_proc(co_diffusion_cus_bridge_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(oxygen)
        call add_proc(reaction_oxygen_cus_co_cus_up, site + (/0, -1, 0, 0/))
    case(empty)
        call add_proc(co_diffusion_cus_cus_down, site + (/0, -1, 0, 0/))
    end select

    select case(get_species(site + (/0, 1, 0, 0/)))
    case(oxygen)
        call add_proc(reaction_oxygen_cus_co_cus_down, site)
    case(empty)
        call add_proc(co_diffusion_cus_cus_up, site)
    end select


end subroutine put_co_ruo2_cus

subroutine take_co_ruo2_cus(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, co, empty)

    ! disable affected processes
    if(avail_sites(co_desorption_cus, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_desorption_cus, site)
    endif

    if(avail_sites(co_diffusion_cus_bridge_left, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(co_diffusion_cus_bridge_left, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(co_diffusion_cus_bridge_right, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(co_diffusion_cus_bridge_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(co_diffusion_cus_cus_down, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(co_diffusion_cus_cus_down, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(co_diffusion_cus_cus_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_diffusion_cus_cus_up, site)
    endif

    if(avail_sites(reaction_oxygen_bridge_co_cus_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(reaction_oxygen_bridge_co_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(reaction_oxygen_bridge_co_cus_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(reaction_oxygen_bridge_co_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(reaction_oxygen_cus_co_cus_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(reaction_oxygen_cus_co_cus_down, site)
    endif

    if(avail_sites(reaction_oxygen_cus_co_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(reaction_oxygen_cus_co_cus_up, site + (/0, -1, 0, 0/))
    endif

    ! enable affected processes
    call add_proc(co_adsorption_cus, site)
    select case(get_species(site + (/1, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(co)
        call add_proc(co_diffusion_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(oxygen)
        call add_proc(oxygen_diffusion_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(empty)
        call add_proc(oxygen_adsorption_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(co)
        call add_proc(co_diffusion_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(oxygen)
        call add_proc(oxygen_diffusion_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(empty)
        call add_proc(oxygen_adsorption_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, 1, 0, 0/)))
    case(co)
        call add_proc(co_diffusion_cus_cus_down, site)
    case(oxygen)
        call add_proc(oxygen_diffusion_cus_cus_down, site)
    case(empty)
        call add_proc(oxygen_adsorption_cus_cus, site)
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(co)
        call add_proc(co_diffusion_cus_cus_up, site + (/0, -1, 0, 0/))
    case(oxygen)
        call add_proc(oxygen_diffusion_cus_cus_up, site + (/0, -1, 0, 0/))
    case(empty)
        call add_proc(oxygen_adsorption_cus_cus, site + (/0, -1, 0, 0/))
    end select


end subroutine take_co_ruo2_cus

subroutine put_oxygen_ruo2_bridge(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, empty, oxygen)

    ! disable affected processes
    if(avail_sites(co_adsorption_bridge, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_adsorption_bridge, site)
    endif

    if(avail_sites(co_diffusion_bridge_bridge_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_diffusion_bridge_bridge_down, site)
    endif

    if(avail_sites(co_diffusion_bridge_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(co_diffusion_bridge_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(co_diffusion_cus_bridge_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_diffusion_cus_bridge_left, site)
    endif

    if(avail_sites(co_diffusion_cus_bridge_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_diffusion_cus_bridge_right, site)
    endif

    if(avail_sites(oxygen_adsorption_bridge_bridge, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_adsorption_bridge_bridge, site)
    endif

    if(avail_sites(oxygen_adsorption_bridge_bridge, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(oxygen_adsorption_bridge_bridge, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(oxygen_adsorption_bridge_cus_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_adsorption_bridge_cus_left, site)
    endif

    if(avail_sites(oxygen_adsorption_bridge_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_adsorption_bridge_cus_right, site)
    endif

    if(avail_sites(oxygen_diffusion_bridge_bridge_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_diffusion_bridge_bridge_down, site)
    endif

    if(avail_sites(oxygen_diffusion_bridge_bridge_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(oxygen_diffusion_bridge_bridge_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(oxygen_diffusion_cus_bridge_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_diffusion_cus_bridge_left, site)
    endif

    if(avail_sites(oxygen_diffusion_cus_bridge_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_diffusion_cus_bridge_right, site)
    endif

    ! enable affected processes
    select case(get_species(site + (/0, 1, 0, 0/)))
    case(co)
        call add_proc(reaction_oxygen_bridge_co_bridge_up, site)
    case(empty)
        call add_proc(oxygen_diffusion_bridge_bridge_up, site)
    case(oxygen)
        call add_proc(oxygen_desorption_bridge_bridge, site)
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(co)
        call add_proc(reaction_oxygen_bridge_co_bridge_down, site + (/0, -1, 0, 0/))
    case(empty)
        call add_proc(oxygen_diffusion_bridge_bridge_down, site + (/0, -1, 0, 0/))
    case(oxygen)
        call add_proc(oxygen_desorption_bridge_bridge, site + (/0, -1, 0, 0/))
    end select

    select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(co)
        call add_proc(reaction_oxygen_bridge_co_cus_left, site)
    case(empty)
        call add_proc(oxygen_diffusion_bridge_cus_left, site)
    case(oxygen)
        call add_proc(oxygen_desorption_bridge_cus_left, site)
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(co)
        call add_proc(reaction_oxygen_bridge_co_cus_right, site)
    case(empty)
        call add_proc(oxygen_diffusion_bridge_cus_right, site)
    case(oxygen)
        call add_proc(oxygen_desorption_bridge_cus_right, site)
    end select


end subroutine put_oxygen_ruo2_bridge

subroutine take_oxygen_ruo2_bridge(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, oxygen, empty)

    ! disable affected processes
    if(avail_sites(oxygen_desorption_bridge_bridge, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_desorption_bridge_bridge, site)
    endif

    if(avail_sites(oxygen_desorption_bridge_bridge, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(oxygen_desorption_bridge_bridge, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(oxygen_desorption_bridge_cus_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_desorption_bridge_cus_left, site)
    endif

    if(avail_sites(oxygen_desorption_bridge_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_desorption_bridge_cus_right, site)
    endif

    if(avail_sites(oxygen_diffusion_bridge_bridge_down, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(oxygen_diffusion_bridge_bridge_down, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(oxygen_diffusion_bridge_bridge_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_diffusion_bridge_bridge_up, site)
    endif

    if(avail_sites(oxygen_diffusion_bridge_cus_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_diffusion_bridge_cus_left, site)
    endif

    if(avail_sites(oxygen_diffusion_bridge_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_diffusion_bridge_cus_right, site)
    endif

    if(avail_sites(reaction_oxygen_bridge_co_bridge_down, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(reaction_oxygen_bridge_co_bridge_down, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(reaction_oxygen_bridge_co_bridge_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(reaction_oxygen_bridge_co_bridge_up, site)
    endif

    if(avail_sites(reaction_oxygen_bridge_co_cus_left, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(reaction_oxygen_bridge_co_cus_left, site)
    endif

    if(avail_sites(reaction_oxygen_bridge_co_cus_right, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(reaction_oxygen_bridge_co_cus_right, site)
    endif

    ! enable affected processes
    call add_proc(co_adsorption_bridge, site)
    select case(get_species(site + (/0, 1, 0, 0/)))
    case(co)
        call add_proc(co_diffusion_bridge_bridge_down, site)
    case(oxygen)
        call add_proc(oxygen_diffusion_bridge_bridge_down, site)
    case(empty)
        call add_proc(oxygen_adsorption_bridge_bridge, site)
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(co)
        call add_proc(co_diffusion_bridge_bridge_up, site + (/0, -1, 0, 0/))
    case(oxygen)
        call add_proc(oxygen_diffusion_bridge_bridge_up, site + (/0, -1, 0, 0/))
    case(empty)
        call add_proc(oxygen_adsorption_bridge_bridge, site + (/0, -1, 0, 0/))
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(co)
        call add_proc(co_diffusion_cus_bridge_left, site)
    case(oxygen)
        call add_proc(oxygen_diffusion_cus_bridge_left, site)
    case(empty)
        call add_proc(oxygen_adsorption_bridge_cus_right, site)
    end select

    select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
    case(co)
        call add_proc(co_diffusion_cus_bridge_right, site)
    case(oxygen)
        call add_proc(oxygen_diffusion_cus_bridge_right, site)
    case(empty)
        call add_proc(oxygen_adsorption_bridge_cus_left, site)
    end select


end subroutine take_oxygen_ruo2_bridge

subroutine put_oxygen_ruo2_cus(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, empty, oxygen)

    ! disable affected processes
    if(avail_sites(co_adsorption_cus, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_adsorption_cus, site)
    endif

    if(avail_sites(co_diffusion_bridge_cus_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(co_diffusion_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(co_diffusion_bridge_cus_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(co_diffusion_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(co_diffusion_cus_cus_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(co_diffusion_cus_cus_down, site)
    endif

    if(avail_sites(co_diffusion_cus_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(co_diffusion_cus_cus_up, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(oxygen_adsorption_bridge_cus_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(oxygen_adsorption_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(oxygen_adsorption_bridge_cus_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(oxygen_adsorption_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(oxygen_adsorption_cus_cus, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_adsorption_cus_cus, site)
    endif

    if(avail_sites(oxygen_adsorption_cus_cus, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(oxygen_adsorption_cus_cus, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(oxygen_diffusion_bridge_cus_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(oxygen_diffusion_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(oxygen_diffusion_bridge_cus_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(oxygen_diffusion_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(oxygen_diffusion_cus_cus_down, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_diffusion_cus_cus_down, site)
    endif

    if(avail_sites(oxygen_diffusion_cus_cus_up, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(oxygen_diffusion_cus_cus_up, site + (/0, -1, 0, 0/))
    endif

    ! enable affected processes
    select case(get_species(site + (/1, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(co)
        call add_proc(reaction_oxygen_cus_co_bridge_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(empty)
        call add_proc(oxygen_diffusion_cus_bridge_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(oxygen)
        call add_proc(oxygen_desorption_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(co)
        call add_proc(reaction_oxygen_cus_co_bridge_left, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(empty)
        call add_proc(oxygen_diffusion_cus_bridge_left, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(oxygen)
        call add_proc(oxygen_desorption_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, 1, 0, 0/)))
    case(co)
        call add_proc(reaction_oxygen_cus_co_cus_up, site)
    case(empty)
        call add_proc(oxygen_diffusion_cus_cus_up, site)
    case(oxygen)
        call add_proc(oxygen_desorption_cus_cus, site)
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(co)
        call add_proc(reaction_oxygen_cus_co_cus_down, site + (/0, -1, 0, 0/))
    case(empty)
        call add_proc(oxygen_diffusion_cus_cus_down, site + (/0, -1, 0, 0/))
    case(oxygen)
        call add_proc(oxygen_desorption_cus_cus, site + (/0, -1, 0, 0/))
    end select


end subroutine put_oxygen_ruo2_cus

subroutine take_oxygen_ruo2_cus(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    ! update lattice
    call replace_species(site, oxygen, empty)

    ! disable affected processes
    if(avail_sites(oxygen_desorption_bridge_cus_left, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(oxygen_desorption_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(oxygen_desorption_bridge_cus_right, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(oxygen_desorption_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(oxygen_desorption_cus_cus, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_desorption_cus_cus, site)
    endif

    if(avail_sites(oxygen_desorption_cus_cus, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(oxygen_desorption_cus_cus, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(oxygen_diffusion_cus_bridge_left, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(oxygen_diffusion_cus_bridge_left, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(oxygen_diffusion_cus_bridge_right, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(oxygen_diffusion_cus_bridge_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(oxygen_diffusion_cus_cus_down, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(oxygen_diffusion_cus_cus_down, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(oxygen_diffusion_cus_cus_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(oxygen_diffusion_cus_cus_up, site)
    endif

    if(avail_sites(reaction_oxygen_cus_co_bridge_left, lattice2nr(site(1) + (0), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(reaction_oxygen_cus_co_bridge_left, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(reaction_oxygen_cus_co_bridge_right, lattice2nr(site(1) + (1), site(2) + (0), site(3) + (0), site(4) + (ruo2_bridge - ruo2_cus)), 2).ne.0)then
        call del_proc(reaction_oxygen_cus_co_bridge_right, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    endif

    if(avail_sites(reaction_oxygen_cus_co_cus_down, lattice2nr(site(1) + (0), site(2) + (-1), site(3) + (0), site(4) + (0)), 2).ne.0)then
        call del_proc(reaction_oxygen_cus_co_cus_down, site + (/0, -1, 0, 0/))
    endif

    if(avail_sites(reaction_oxygen_cus_co_cus_up, lattice2nr(site(1), site(2), site(3), site(4)), 2).ne.0)then
        call del_proc(reaction_oxygen_cus_co_cus_up, site)
    endif

    ! enable affected processes
    call add_proc(co_adsorption_cus, site)
    select case(get_species(site + (/1, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(co)
        call add_proc(co_diffusion_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(oxygen)
        call add_proc(oxygen_diffusion_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    case(empty)
        call add_proc(oxygen_adsorption_bridge_cus_left, site + (/1, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, 0, 0, ruo2_bridge - ruo2_cus/)))
    case(co)
        call add_proc(co_diffusion_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(oxygen)
        call add_proc(oxygen_diffusion_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    case(empty)
        call add_proc(oxygen_adsorption_bridge_cus_right, site + (/0, 0, 0, ruo2_bridge - ruo2_cus/))
    end select

    select case(get_species(site + (/0, 1, 0, 0/)))
    case(co)
        call add_proc(co_diffusion_cus_cus_down, site)
    case(oxygen)
        call add_proc(oxygen_diffusion_cus_cus_down, site)
    case(empty)
        call add_proc(oxygen_adsorption_cus_cus, site)
    end select

    select case(get_species(site + (/0, -1, 0, 0/)))
    case(co)
        call add_proc(co_diffusion_cus_cus_up, site + (/0, -1, 0, 0/))
    case(oxygen)
        call add_proc(oxygen_diffusion_cus_cus_up, site + (/0, -1, 0, 0/))
    case(empty)
        call add_proc(oxygen_adsorption_cus_cus, site + (/0, -1, 0, 0/))
    end select


end subroutine take_oxygen_ruo2_cus

subroutine touchup_ruo2_bridge(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    if (can_do(co_adsorption_bridge, site)) then
        call del_proc(co_adsorption_bridge, site)
    endif
    if (can_do(co_adsorption_cus, site)) then
        call del_proc(co_adsorption_cus, site)
    endif
    if (can_do(co_desorption_bridge, site)) then
        call del_proc(co_desorption_bridge, site)
    endif
    if (can_do(co_desorption_cus, site)) then
        call del_proc(co_desorption_cus, site)
    endif
    if (can_do(co_diffusion_bridge_bridge_down, site)) then
        call del_proc(co_diffusion_bridge_bridge_down, site)
    endif
    if (can_do(co_diffusion_bridge_bridge_up, site)) then
        call del_proc(co_diffusion_bridge_bridge_up, site)
    endif
    if (can_do(co_diffusion_bridge_cus_left, site)) then
        call del_proc(co_diffusion_bridge_cus_left, site)
    endif
    if (can_do(co_diffusion_bridge_cus_right, site)) then
        call del_proc(co_diffusion_bridge_cus_right, site)
    endif
    if (can_do(co_diffusion_cus_bridge_left, site)) then
        call del_proc(co_diffusion_cus_bridge_left, site)
    endif
    if (can_do(co_diffusion_cus_bridge_right, site)) then
        call del_proc(co_diffusion_cus_bridge_right, site)
    endif
    if (can_do(co_diffusion_cus_cus_down, site)) then
        call del_proc(co_diffusion_cus_cus_down, site)
    endif
    if (can_do(co_diffusion_cus_cus_up, site)) then
        call del_proc(co_diffusion_cus_cus_up, site)
    endif
    if (can_do(oxygen_adsorption_bridge_bridge, site)) then
        call del_proc(oxygen_adsorption_bridge_bridge, site)
    endif
    if (can_do(oxygen_adsorption_bridge_cus_left, site)) then
        call del_proc(oxygen_adsorption_bridge_cus_left, site)
    endif
    if (can_do(oxygen_adsorption_bridge_cus_right, site)) then
        call del_proc(oxygen_adsorption_bridge_cus_right, site)
    endif
    if (can_do(oxygen_adsorption_cus_cus, site)) then
        call del_proc(oxygen_adsorption_cus_cus, site)
    endif
    if (can_do(oxygen_desorption_bridge_bridge, site)) then
        call del_proc(oxygen_desorption_bridge_bridge, site)
    endif
    if (can_do(oxygen_desorption_bridge_cus_left, site)) then
        call del_proc(oxygen_desorption_bridge_cus_left, site)
    endif
    if (can_do(oxygen_desorption_bridge_cus_right, site)) then
        call del_proc(oxygen_desorption_bridge_cus_right, site)
    endif
    if (can_do(oxygen_desorption_cus_cus, site)) then
        call del_proc(oxygen_desorption_cus_cus, site)
    endif
    if (can_do(oxygen_diffusion_bridge_bridge_down, site)) then
        call del_proc(oxygen_diffusion_bridge_bridge_down, site)
    endif
    if (can_do(oxygen_diffusion_bridge_bridge_up, site)) then
        call del_proc(oxygen_diffusion_bridge_bridge_up, site)
    endif
    if (can_do(oxygen_diffusion_bridge_cus_left, site)) then
        call del_proc(oxygen_diffusion_bridge_cus_left, site)
    endif
    if (can_do(oxygen_diffusion_bridge_cus_right, site)) then
        call del_proc(oxygen_diffusion_bridge_cus_right, site)
    endif
    if (can_do(oxygen_diffusion_cus_bridge_left, site)) then
        call del_proc(oxygen_diffusion_cus_bridge_left, site)
    endif
    if (can_do(oxygen_diffusion_cus_bridge_right, site)) then
        call del_proc(oxygen_diffusion_cus_bridge_right, site)
    endif
    if (can_do(oxygen_diffusion_cus_cus_down, site)) then
        call del_proc(oxygen_diffusion_cus_cus_down, site)
    endif
    if (can_do(oxygen_diffusion_cus_cus_up, site)) then
        call del_proc(oxygen_diffusion_cus_cus_up, site)
    endif
    if (can_do(reaction_oxygen_bridge_co_bridge_down, site)) then
        call del_proc(reaction_oxygen_bridge_co_bridge_down, site)
    endif
    if (can_do(reaction_oxygen_bridge_co_bridge_up, site)) then
        call del_proc(reaction_oxygen_bridge_co_bridge_up, site)
    endif
    if (can_do(reaction_oxygen_bridge_co_cus_left, site)) then
        call del_proc(reaction_oxygen_bridge_co_cus_left, site)
    endif
    if (can_do(reaction_oxygen_bridge_co_cus_right, site)) then
        call del_proc(reaction_oxygen_bridge_co_cus_right, site)
    endif
    if (can_do(reaction_oxygen_cus_co_bridge_left, site)) then
        call del_proc(reaction_oxygen_cus_co_bridge_left, site)
    endif
    if (can_do(reaction_oxygen_cus_co_bridge_right, site)) then
        call del_proc(reaction_oxygen_cus_co_bridge_right, site)
    endif
    if (can_do(reaction_oxygen_cus_co_cus_down, site)) then
        call del_proc(reaction_oxygen_cus_co_cus_down, site)
    endif
    if (can_do(reaction_oxygen_cus_co_cus_up, site)) then
        call del_proc(reaction_oxygen_cus_co_cus_up, site)
    endif
    select case(get_species(site))
    case(co)
        call add_proc(co_desorption_bridge, site)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(oxygen)
            call add_proc(reaction_oxygen_bridge_co_bridge_down, site)
        case(empty)
            call add_proc(co_diffusion_bridge_bridge_up, site)
        end select

        select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
        case(oxygen)
            call add_proc(reaction_oxygen_cus_co_bridge_right, site)
        case(empty)
            call add_proc(co_diffusion_bridge_cus_left, site)
        end select

        select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
        case(oxygen)
            call add_proc(reaction_oxygen_cus_co_bridge_left, site)
        case(empty)
            call add_proc(co_diffusion_bridge_cus_right, site)
        end select

    case(oxygen)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(co)
            call add_proc(reaction_oxygen_bridge_co_bridge_up, site)
        case(empty)
            call add_proc(oxygen_diffusion_bridge_bridge_up, site)
        case(oxygen)
            call add_proc(oxygen_desorption_bridge_bridge, site)
        end select

        select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
        case(co)
            call add_proc(reaction_oxygen_bridge_co_cus_left, site)
        case(empty)
            call add_proc(oxygen_diffusion_bridge_cus_left, site)
        case(oxygen)
            call add_proc(oxygen_desorption_bridge_cus_left, site)
        end select

        select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
        case(co)
            call add_proc(reaction_oxygen_bridge_co_cus_right, site)
        case(empty)
            call add_proc(oxygen_diffusion_bridge_cus_right, site)
        case(oxygen)
            call add_proc(oxygen_desorption_bridge_cus_right, site)
        end select

    case(empty)
        call add_proc(co_adsorption_bridge, site)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(co)
            call add_proc(co_diffusion_bridge_bridge_down, site)
        case(oxygen)
            call add_proc(oxygen_diffusion_bridge_bridge_down, site)
        case(empty)
            call add_proc(oxygen_adsorption_bridge_bridge, site)
        end select

        select case(get_species(site + (/0, 0, 0, ruo2_cus - ruo2_bridge/)))
        case(co)
            call add_proc(co_diffusion_cus_bridge_left, site)
        case(oxygen)
            call add_proc(oxygen_diffusion_cus_bridge_left, site)
        case(empty)
            call add_proc(oxygen_adsorption_bridge_cus_right, site)
        end select

        select case(get_species(site + (/-1, 0, 0, ruo2_cus - ruo2_bridge/)))
        case(co)
            call add_proc(co_diffusion_cus_bridge_right, site)
        case(oxygen)
            call add_proc(oxygen_diffusion_cus_bridge_right, site)
        case(empty)
            call add_proc(oxygen_adsorption_bridge_cus_left, site)
        end select

    end select

end subroutine touchup_ruo2_bridge

subroutine touchup_ruo2_cus(site)

    integer(kind=iint), dimension(4), intent(in) :: site

    if (can_do(co_adsorption_bridge, site)) then
        call del_proc(co_adsorption_bridge, site)
    endif
    if (can_do(co_adsorption_cus, site)) then
        call del_proc(co_adsorption_cus, site)
    endif
    if (can_do(co_desorption_bridge, site)) then
        call del_proc(co_desorption_bridge, site)
    endif
    if (can_do(co_desorption_cus, site)) then
        call del_proc(co_desorption_cus, site)
    endif
    if (can_do(co_diffusion_bridge_bridge_down, site)) then
        call del_proc(co_diffusion_bridge_bridge_down, site)
    endif
    if (can_do(co_diffusion_bridge_bridge_up, site)) then
        call del_proc(co_diffusion_bridge_bridge_up, site)
    endif
    if (can_do(co_diffusion_bridge_cus_left, site)) then
        call del_proc(co_diffusion_bridge_cus_left, site)
    endif
    if (can_do(co_diffusion_bridge_cus_right, site)) then
        call del_proc(co_diffusion_bridge_cus_right, site)
    endif
    if (can_do(co_diffusion_cus_bridge_left, site)) then
        call del_proc(co_diffusion_cus_bridge_left, site)
    endif
    if (can_do(co_diffusion_cus_bridge_right, site)) then
        call del_proc(co_diffusion_cus_bridge_right, site)
    endif
    if (can_do(co_diffusion_cus_cus_down, site)) then
        call del_proc(co_diffusion_cus_cus_down, site)
    endif
    if (can_do(co_diffusion_cus_cus_up, site)) then
        call del_proc(co_diffusion_cus_cus_up, site)
    endif
    if (can_do(oxygen_adsorption_bridge_bridge, site)) then
        call del_proc(oxygen_adsorption_bridge_bridge, site)
    endif
    if (can_do(oxygen_adsorption_bridge_cus_left, site)) then
        call del_proc(oxygen_adsorption_bridge_cus_left, site)
    endif
    if (can_do(oxygen_adsorption_bridge_cus_right, site)) then
        call del_proc(oxygen_adsorption_bridge_cus_right, site)
    endif
    if (can_do(oxygen_adsorption_cus_cus, site)) then
        call del_proc(oxygen_adsorption_cus_cus, site)
    endif
    if (can_do(oxygen_desorption_bridge_bridge, site)) then
        call del_proc(oxygen_desorption_bridge_bridge, site)
    endif
    if (can_do(oxygen_desorption_bridge_cus_left, site)) then
        call del_proc(oxygen_desorption_bridge_cus_left, site)
    endif
    if (can_do(oxygen_desorption_bridge_cus_right, site)) then
        call del_proc(oxygen_desorption_bridge_cus_right, site)
    endif
    if (can_do(oxygen_desorption_cus_cus, site)) then
        call del_proc(oxygen_desorption_cus_cus, site)
    endif
    if (can_do(oxygen_diffusion_bridge_bridge_down, site)) then
        call del_proc(oxygen_diffusion_bridge_bridge_down, site)
    endif
    if (can_do(oxygen_diffusion_bridge_bridge_up, site)) then
        call del_proc(oxygen_diffusion_bridge_bridge_up, site)
    endif
    if (can_do(oxygen_diffusion_bridge_cus_left, site)) then
        call del_proc(oxygen_diffusion_bridge_cus_left, site)
    endif
    if (can_do(oxygen_diffusion_bridge_cus_right, site)) then
        call del_proc(oxygen_diffusion_bridge_cus_right, site)
    endif
    if (can_do(oxygen_diffusion_cus_bridge_left, site)) then
        call del_proc(oxygen_diffusion_cus_bridge_left, site)
    endif
    if (can_do(oxygen_diffusion_cus_bridge_right, site)) then
        call del_proc(oxygen_diffusion_cus_bridge_right, site)
    endif
    if (can_do(oxygen_diffusion_cus_cus_down, site)) then
        call del_proc(oxygen_diffusion_cus_cus_down, site)
    endif
    if (can_do(oxygen_diffusion_cus_cus_up, site)) then
        call del_proc(oxygen_diffusion_cus_cus_up, site)
    endif
    if (can_do(reaction_oxygen_bridge_co_bridge_down, site)) then
        call del_proc(reaction_oxygen_bridge_co_bridge_down, site)
    endif
    if (can_do(reaction_oxygen_bridge_co_bridge_up, site)) then
        call del_proc(reaction_oxygen_bridge_co_bridge_up, site)
    endif
    if (can_do(reaction_oxygen_bridge_co_cus_left, site)) then
        call del_proc(reaction_oxygen_bridge_co_cus_left, site)
    endif
    if (can_do(reaction_oxygen_bridge_co_cus_right, site)) then
        call del_proc(reaction_oxygen_bridge_co_cus_right, site)
    endif
    if (can_do(reaction_oxygen_cus_co_bridge_left, site)) then
        call del_proc(reaction_oxygen_cus_co_bridge_left, site)
    endif
    if (can_do(reaction_oxygen_cus_co_bridge_right, site)) then
        call del_proc(reaction_oxygen_cus_co_bridge_right, site)
    endif
    if (can_do(reaction_oxygen_cus_co_cus_down, site)) then
        call del_proc(reaction_oxygen_cus_co_cus_down, site)
    endif
    if (can_do(reaction_oxygen_cus_co_cus_up, site)) then
        call del_proc(reaction_oxygen_cus_co_cus_up, site)
    endif
    select case(get_species(site))
    case(co)
        call add_proc(co_desorption_cus, site)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(oxygen)
            call add_proc(reaction_oxygen_cus_co_cus_down, site)
        case(empty)
            call add_proc(co_diffusion_cus_cus_up, site)
        end select

    case(oxygen)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(co)
            call add_proc(reaction_oxygen_cus_co_cus_up, site)
        case(empty)
            call add_proc(oxygen_diffusion_cus_cus_up, site)
        case(oxygen)
            call add_proc(oxygen_desorption_cus_cus, site)
        end select

    case(empty)
        call add_proc(co_adsorption_cus, site)
        select case(get_species(site + (/0, 1, 0, 0/)))
        case(co)
            call add_proc(co_diffusion_cus_cus_down, site)
        case(oxygen)
            call add_proc(oxygen_diffusion_cus_cus_down, site)
        case(empty)
            call add_proc(oxygen_adsorption_cus_cus, site)
        end select

    end select

end subroutine touchup_ruo2_cus

end module proclist
