#!/usr/bin/env python

import os
import optparse

parser = optparse.OptionParser("""Usage: %prog [help] (edit | view | export) [options]""")

options, args = parser.parse_args()

if len(args) < 1 :
    parser.error('Command expected')

if args[0] == 'help':
    if len(args) < 2 :
        parser.error('Which help do you  want?')
    if args[1] == 'edit' :
        print("""Usage: %prog edit <xml-file>
                        open the kmos xml-file in a GUI to edit
                        the model.""")
    elif args[1] == 'view' :
        print("""Usage: %prog view
                        Except a kmc_model.so and kmc_settings in the 
                        same directory and will start to simulate the
                        model visually""")
    elif args[1] == 'edit' :
        print("""Usage: %prog export <xml-file> <export-path>
                        Take a kmos xml-file and export all generated
                        source code to the export-path. There it will
                        try to build the kmc_model.so.""")

elif args[0] == 'edit':
    if len(args) < 2 :
        print('No XML file provided, starting a new model.')
        args.append('')
    os.system('kmos-editor %s' % args[1])
elif args[0] == 'export':
    if len(args) < 3 :
        parser.error('XML file and export path expected.')
    os.system('kmos-export-program %s %s' % (args[1], args[2]))
elif args[0] == 'view':
    os.system('kmos-view')
