#!/usr/bin/env python

from kmos.view import KMC_Viewer
import gtk
import gobject

if __name__ == '__main__':
    gobject.threads_init()
    viewer = KMC_Viewer()
    viewer.model.start()
    viewer.viewbox.start()
    print('started model and viewbox processes')
    gtk.main()
    print('gtk.main stopped')
