#!/usr/bin/python
#    Copyright 2009-2011 Max J. Hoffmann (mjhoffmann@gmail.com)
#    This file is part of kmos.
#
#    kmos is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    kmos is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with kmos.  If not, see <http://www.gnu.org/licenses/>.

def main():
    import optparse

    import kmos.gui

    parser = optparse.OptionParser()
    parser.add_option('-o', '--open',
                      dest='xml_file',
                      help='Immediately import kmos XML file')
    parser.add_option('-x', '--export-dir',
                      dest='export_dir',
                      type=str)
    (options, args) = parser.parse_args()
    editor = kmos.gui.Editor()
    if len(args) >= 1:
        options.xml_file = args[0]

    if options.xml_file:
        editor.import_xml_file(options.xml_file)
        editor.toast('Imported %s' % options.xml_file)
    else:
        editor.add_defaults()
        editor.saved_state = str(editor.project_tree)
    if hasattr(options, 'export_dir') and options.export_dir:
        print('Exporting right-away')
        editor.on_btn_export_src__clicked(button='', export_dir=options.export_dir)
        exit()
    editor.show_and_loop()

if __name__ == '__main__':
    main()
