#!/bin/bash -eu
#    Copyright 2009-2012 Max J. Hoffmann (mjhoffmann@gmail.com)
#    This file is part of kmos.
#
#    kmos is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    kmos is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with kmos.  If not, see <http://www.gnu.org/licenses/>.

gfortran -c kind_values_f2py.f90 -g -pg
gfortran -c base.f90 -cpp -g -pg
gfortran -c lattice.f90 -g -pg
gfortran -c proclist.f90 -g -pg
gfortran -o run_kmc run_kmc.f90 kind_values_f2py.o base.o lattice.o proclist.o -g -pg
