#!/usr/bin/env python
#    Copyright 2009-2011 Max J. Hoffmann (mjhoffmann@gmail.com)
#    This file is part of kmos.
#
#    kmos is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    kmos is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with kmos.  If not, see <http://www.gnu.org/licenses/>.

from kmos.view import KMC_Viewer
import gtk
import gobject

def main():
    gobject.threads_init()
    viewer = KMC_Viewer()
    viewer.model.start()
    viewer.viewbox.start()
    print('started model and viewbox processes')
    gtk.main()
    print('gtk.main stopped')

if __name__ == '__main__':
    main()
