!  This file was generated by kMOS (kMC modelling on steroids)
!  written by Max J. Hoffmann mjhoffmann@gmail.com (C) 2009-2013.
!  The model was written by Max J. Hoffmann.

!  This file is part of kmos.
!
!  kmos is free software; you can redistribute it and/or modify
!  it under the terms of the GNU General Public License as published by
!  the Free Software Foundation; either version 2 of the License, or
!  (at your option) any later version.
!
!  kmos is distributed in the hope that it will be useful,
!  but WITHOUT ANY WARRANTY; without even the implied warranty of
!  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!  GNU General Public License for more details.
!
!  You should have received a copy of the GNU General Public License
!  along with kmos; if not, write to the Free Software
!  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301
!  USA
module proclist_pars
use kind_values
use base, only: &
    rates
use proclist_constants, only: &
    co, &
    empty, &
    oxygen, &
    co_adsorption_bridge, &
    co_adsorption_cus, &
    co_desorption_bridge, &
    co_desorption_cus, &
    co_diffusion_bridge_bridge_down, &
    co_diffusion_bridge_bridge_up, &
    co_diffusion_bridge_cus_left, &
    co_diffusion_bridge_cus_right, &
    co_diffusion_cus_bridge_left, &
    co_diffusion_cus_bridge_right, &
    co_diffusion_cus_cus_down, &
    co_diffusion_cus_cus_up, &
    oxygen_adsorption_bridge_bridge, &
    oxygen_adsorption_bridge_cus_le0000, &
    oxygen_adsorption_bridge_cus_ri0000, &
    oxygen_adsorption_cus_cus, &
    oxygen_desorption_bridge_bridge, &
    oxygen_desorption_bridge_cus_le0000, &
    oxygen_desorption_bridge_cus_ri0000, &
    oxygen_desorption_cus_cus, &
    oxygen_diffusion_bridge_bridge_0000, &
    oxygen_diffusion_bridge_bridge_0001, &
    oxygen_diffusion_bridge_cus_lef0000, &
    oxygen_diffusion_bridge_cus_rig0000, &
    oxygen_diffusion_cus_bridge_lef0000, &
    oxygen_diffusion_cus_bridge_rig0000, &
    oxygen_diffusion_cus_cus_down, &
    oxygen_diffusion_cus_cus_up, &
    reaction_oxygen_bridge_co_bridg0000, &
    reaction_oxygen_bridge_co_bridg0001, &
    reaction_oxygen_bridge_co_cus_l0000, &
    reaction_oxygen_bridge_co_cus_r0000, &
    reaction_oxygen_cus_co_bridge_l0000, &
    reaction_oxygen_cus_co_bridge_r0000, &
    reaction_oxygen_cus_co_cus_down, &
    reaction_oxygen_cus_co_cus_up
use lattice, only: &
    ruo2, &
    ruo2_bridge, &
    ruo2_cus, &
    get_species

implicit none
private :: rate_co_adsorption_bridge, rate_co_adsorption_cus, rate_co_desorption_bridge, rate_co_desorption_cus, rate_co_diffusion_bridge_bridge_down, rate_co_diffusion_bridge_bridge_up, rate_co_diffusion_bridge_cus_left, rate_co_diffusion_bridge_cus_right, rate_co_diffusion_cus_bridge_left, rate_co_diffusion_cus_bridge_right, rate_co_diffusion_cus_cus_down, rate_co_diffusion_cus_cus_up, rate_oxygen_adsorption_bridge_bridge, rate_oxygen_adsorption_bridge_cus_le0000, rate_oxygen_adsorption_bridge_cus_ri0000, rate_oxygen_adsorption_cus_cus, rate_oxygen_desorption_bridge_bridge, rate_oxygen_desorption_bridge_cus_le0000, rate_oxygen_desorption_bridge_cus_ri0000, rate_oxygen_desorption_cus_cus, rate_oxygen_diffusion_bridge_bridge_0000, rate_oxygen_diffusion_bridge_bridge_0001, rate_oxygen_diffusion_bridge_cus_lef0000, rate_oxygen_diffusion_bridge_cus_rig0000, rate_oxygen_diffusion_cus_bridge_lef0000, rate_oxygen_diffusion_cus_bridge_rig0000, rate_oxygen_diffusion_cus_cus_down, rate_oxygen_diffusion_cus_cus_up, rate_reaction_oxygen_bridge_co_bridg0000, rate_reaction_oxygen_bridge_co_bridg0001, rate_reaction_oxygen_bridge_co_cus_l0000, rate_reaction_oxygen_bridge_co_cus_r0000, rate_reaction_oxygen_cus_co_bridge_l0000, rate_reaction_oxygen_cus_co_bridge_r0000, rate_reaction_oxygen_cus_co_cus_down, rate_reaction_oxygen_cus_co_cus_up

! User parameters
integer(kind=iint), public :: A = 1
integer(kind=iint), public :: E_co_bridge = 2
integer(kind=iint), public :: E_co_cus = 3
integer(kind=iint), public :: E_o_bridge_bridge = 4
integer(kind=iint), public :: E_o_cus_bridge = 5
integer(kind=iint), public :: E_o_cus_cus = 6
integer(kind=iint), public :: T = 7
integer(kind=iint), public :: lattice_size = 8
integer(kind=iint), public :: m_co = 9
integer(kind=iint), public :: m_o2 = 10
integer(kind=iint), public :: p_co = 11
integer(kind=iint), public :: p_o2 = 12
integer(kind=iint), public :: print_every = 13
integer(kind=iint), public :: total_steps = 14
real(kind=rdouble), public, dimension(14) :: userpar

! Constants

! Species masses
character(len=0), parameter, public :: byst_co_adsorption_bridge = ""
character(len=0), parameter, public :: byst_co_adsorption_cus = ""
character(len=0), parameter, public :: byst_co_desorption_bridge = ""
character(len=0), parameter, public :: byst_co_desorption_cus = ""
character(len=0), parameter, public :: byst_co_diffusion_bridge_bridge_down = ""
character(len=0), parameter, public :: byst_co_diffusion_bridge_bridge_up = ""
character(len=0), parameter, public :: byst_co_diffusion_bridge_cus_left = ""
character(len=0), parameter, public :: byst_co_diffusion_bridge_cus_right = ""
character(len=0), parameter, public :: byst_co_diffusion_cus_bridge_left = ""
character(len=0), parameter, public :: byst_co_diffusion_cus_bridge_right = ""
character(len=0), parameter, public :: byst_co_diffusion_cus_cus_down = ""
character(len=0), parameter, public :: byst_co_diffusion_cus_cus_up = ""
character(len=0), parameter, public :: byst_oxygen_adsorption_bridge_bridge = ""
character(len=0), parameter, public :: byst_oxygen_adsorption_bridge_cus_le0000 = ""
character(len=0), parameter, public :: byst_oxygen_adsorption_bridge_cus_ri0000 = ""
character(len=0), parameter, public :: byst_oxygen_adsorption_cus_cus = ""
character(len=0), parameter, public :: byst_oxygen_desorption_bridge_bridge = ""
character(len=0), parameter, public :: byst_oxygen_desorption_bridge_cus_le0000 = ""
character(len=0), parameter, public :: byst_oxygen_desorption_bridge_cus_ri0000 = ""
character(len=0), parameter, public :: byst_oxygen_desorption_cus_cus = ""
character(len=0), parameter, public :: byst_oxygen_diffusion_bridge_bridge_0000 = ""
character(len=0), parameter, public :: byst_oxygen_diffusion_bridge_bridge_0001 = ""
character(len=0), parameter, public :: byst_oxygen_diffusion_bridge_cus_lef0000 = ""
character(len=0), parameter, public :: byst_oxygen_diffusion_bridge_cus_rig0000 = ""
character(len=0), parameter, public :: byst_oxygen_diffusion_cus_bridge_lef0000 = ""
character(len=0), parameter, public :: byst_oxygen_diffusion_cus_bridge_rig0000 = ""
character(len=0), parameter, public :: byst_oxygen_diffusion_cus_cus_down = ""
character(len=0), parameter, public :: byst_oxygen_diffusion_cus_cus_up = ""
character(len=0), parameter, public :: byst_reaction_oxygen_bridge_co_bridg0000 = ""
character(len=0), parameter, public :: byst_reaction_oxygen_bridge_co_bridg0001 = ""
character(len=0), parameter, public :: byst_reaction_oxygen_bridge_co_cus_l0000 = ""
character(len=0), parameter, public :: byst_reaction_oxygen_bridge_co_cus_r0000 = ""
character(len=0), parameter, public :: byst_reaction_oxygen_cus_co_bridge_l0000 = ""
character(len=0), parameter, public :: byst_reaction_oxygen_cus_co_bridge_r0000 = ""
character(len=0), parameter, public :: byst_reaction_oxygen_cus_co_cus_down = ""
character(len=0), parameter, public :: byst_reaction_oxygen_cus_co_cus_up = ""

contains
subroutine update_user_parameter(param,val)
    integer(kind=iint), intent(in) :: param
    real(kind=rdouble), intent(in) :: val
    userpar(param) = val
end subroutine update_user_parameter

subroutine get_user_parameter(param,val)
    integer(kind=iint), intent(in) :: param
    real(kind=rdouble), intent(out) :: val
    val = userpar(param)
end subroutine get_user_parameter


function gr_co_adsorption_bridge(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_co_adsorption_bridge


    gr_co_adsorption_bridge = rate_co_adsorption_bridge()
    return

end function gr_co_adsorption_bridge

function rate_co_adsorption_bridge()


    real(kind=rdouble) :: rate_co_adsorption_bridge
    rate_co_adsorption_bridge = rates(co_adsorption_bridge)
    return

end function rate_co_adsorption_bridge


function gr_co_adsorption_cus(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_co_adsorption_cus


    gr_co_adsorption_cus = rate_co_adsorption_cus()
    return

end function gr_co_adsorption_cus

function rate_co_adsorption_cus()


    real(kind=rdouble) :: rate_co_adsorption_cus
    rate_co_adsorption_cus = rates(co_adsorption_cus)
    return

end function rate_co_adsorption_cus


function gr_co_desorption_bridge(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_co_desorption_bridge


    gr_co_desorption_bridge = rate_co_desorption_bridge()
    return

end function gr_co_desorption_bridge

function rate_co_desorption_bridge()


    real(kind=rdouble) :: rate_co_desorption_bridge
    rate_co_desorption_bridge = rates(co_desorption_bridge)
    return

end function rate_co_desorption_bridge


function gr_co_desorption_cus(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_co_desorption_cus


    gr_co_desorption_cus = rate_co_desorption_cus()
    return

end function gr_co_desorption_cus

function rate_co_desorption_cus()


    real(kind=rdouble) :: rate_co_desorption_cus
    rate_co_desorption_cus = rates(co_desorption_cus)
    return

end function rate_co_desorption_cus


function gr_co_diffusion_bridge_bridge_down(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_co_diffusion_bridge_bridge_down


    gr_co_diffusion_bridge_bridge_down = rate_co_diffusion_bridge_bridge_down()
    return

end function gr_co_diffusion_bridge_bridge_down

function rate_co_diffusion_bridge_bridge_down()


    real(kind=rdouble) :: rate_co_diffusion_bridge_bridge_down
    rate_co_diffusion_bridge_bridge_down = rates(co_diffusion_bridge_bridge_down)
    return

end function rate_co_diffusion_bridge_bridge_down


function gr_co_diffusion_bridge_bridge_up(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_co_diffusion_bridge_bridge_up


    gr_co_diffusion_bridge_bridge_up = rate_co_diffusion_bridge_bridge_up()
    return

end function gr_co_diffusion_bridge_bridge_up

function rate_co_diffusion_bridge_bridge_up()


    real(kind=rdouble) :: rate_co_diffusion_bridge_bridge_up
    rate_co_diffusion_bridge_bridge_up = rates(co_diffusion_bridge_bridge_up)
    return

end function rate_co_diffusion_bridge_bridge_up


function gr_co_diffusion_bridge_cus_left(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_co_diffusion_bridge_cus_left


    gr_co_diffusion_bridge_cus_left = rate_co_diffusion_bridge_cus_left()
    return

end function gr_co_diffusion_bridge_cus_left

function rate_co_diffusion_bridge_cus_left()


    real(kind=rdouble) :: rate_co_diffusion_bridge_cus_left
    rate_co_diffusion_bridge_cus_left = rates(co_diffusion_bridge_cus_left)
    return

end function rate_co_diffusion_bridge_cus_left


function gr_co_diffusion_bridge_cus_right(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_co_diffusion_bridge_cus_right


    gr_co_diffusion_bridge_cus_right = rate_co_diffusion_bridge_cus_right()
    return

end function gr_co_diffusion_bridge_cus_right

function rate_co_diffusion_bridge_cus_right()


    real(kind=rdouble) :: rate_co_diffusion_bridge_cus_right
    rate_co_diffusion_bridge_cus_right = rates(co_diffusion_bridge_cus_right)
    return

end function rate_co_diffusion_bridge_cus_right


function gr_co_diffusion_cus_bridge_left(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_co_diffusion_cus_bridge_left


    gr_co_diffusion_cus_bridge_left = rate_co_diffusion_cus_bridge_left()
    return

end function gr_co_diffusion_cus_bridge_left

function rate_co_diffusion_cus_bridge_left()


    real(kind=rdouble) :: rate_co_diffusion_cus_bridge_left
    rate_co_diffusion_cus_bridge_left = rates(co_diffusion_cus_bridge_left)
    return

end function rate_co_diffusion_cus_bridge_left


function gr_co_diffusion_cus_bridge_right(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_co_diffusion_cus_bridge_right


    gr_co_diffusion_cus_bridge_right = rate_co_diffusion_cus_bridge_right()
    return

end function gr_co_diffusion_cus_bridge_right

function rate_co_diffusion_cus_bridge_right()


    real(kind=rdouble) :: rate_co_diffusion_cus_bridge_right
    rate_co_diffusion_cus_bridge_right = rates(co_diffusion_cus_bridge_right)
    return

end function rate_co_diffusion_cus_bridge_right


function gr_co_diffusion_cus_cus_down(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_co_diffusion_cus_cus_down


    gr_co_diffusion_cus_cus_down = rate_co_diffusion_cus_cus_down()
    return

end function gr_co_diffusion_cus_cus_down

function rate_co_diffusion_cus_cus_down()


    real(kind=rdouble) :: rate_co_diffusion_cus_cus_down
    rate_co_diffusion_cus_cus_down = rates(co_diffusion_cus_cus_down)
    return

end function rate_co_diffusion_cus_cus_down


function gr_co_diffusion_cus_cus_up(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_co_diffusion_cus_cus_up


    gr_co_diffusion_cus_cus_up = rate_co_diffusion_cus_cus_up()
    return

end function gr_co_diffusion_cus_cus_up

function rate_co_diffusion_cus_cus_up()


    real(kind=rdouble) :: rate_co_diffusion_cus_cus_up
    rate_co_diffusion_cus_cus_up = rates(co_diffusion_cus_cus_up)
    return

end function rate_co_diffusion_cus_cus_up


function gr_oxygen_adsorption_bridge_bridge(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_adsorption_bridge_bridge


    gr_oxygen_adsorption_bridge_bridge = rate_oxygen_adsorption_bridge_bridge()
    return

end function gr_oxygen_adsorption_bridge_bridge

function rate_oxygen_adsorption_bridge_bridge()


    real(kind=rdouble) :: rate_oxygen_adsorption_bridge_bridge
    rate_oxygen_adsorption_bridge_bridge = rates(oxygen_adsorption_bridge_bridge)
    return

end function rate_oxygen_adsorption_bridge_bridge


function gr_oxygen_adsorption_bridge_cus_le0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_adsorption_bridge_cus_le0000


    gr_oxygen_adsorption_bridge_cus_le0000 = rate_oxygen_adsorption_bridge_cus_le0000()
    return

end function gr_oxygen_adsorption_bridge_cus_le0000

function rate_oxygen_adsorption_bridge_cus_le0000()


    real(kind=rdouble) :: rate_oxygen_adsorption_bridge_cus_le0000
    rate_oxygen_adsorption_bridge_cus_le0000 = rates(oxygen_adsorption_bridge_cus_le0000)
    return

end function rate_oxygen_adsorption_bridge_cus_le0000


function gr_oxygen_adsorption_bridge_cus_ri0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_adsorption_bridge_cus_ri0000


    gr_oxygen_adsorption_bridge_cus_ri0000 = rate_oxygen_adsorption_bridge_cus_ri0000()
    return

end function gr_oxygen_adsorption_bridge_cus_ri0000

function rate_oxygen_adsorption_bridge_cus_ri0000()


    real(kind=rdouble) :: rate_oxygen_adsorption_bridge_cus_ri0000
    rate_oxygen_adsorption_bridge_cus_ri0000 = rates(oxygen_adsorption_bridge_cus_ri0000)
    return

end function rate_oxygen_adsorption_bridge_cus_ri0000


function gr_oxygen_adsorption_cus_cus(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_adsorption_cus_cus


    gr_oxygen_adsorption_cus_cus = rate_oxygen_adsorption_cus_cus()
    return

end function gr_oxygen_adsorption_cus_cus

function rate_oxygen_adsorption_cus_cus()


    real(kind=rdouble) :: rate_oxygen_adsorption_cus_cus
    rate_oxygen_adsorption_cus_cus = rates(oxygen_adsorption_cus_cus)
    return

end function rate_oxygen_adsorption_cus_cus


function gr_oxygen_desorption_bridge_bridge(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_desorption_bridge_bridge


    gr_oxygen_desorption_bridge_bridge = rate_oxygen_desorption_bridge_bridge()
    return

end function gr_oxygen_desorption_bridge_bridge

function rate_oxygen_desorption_bridge_bridge()


    real(kind=rdouble) :: rate_oxygen_desorption_bridge_bridge
    rate_oxygen_desorption_bridge_bridge = rates(oxygen_desorption_bridge_bridge)
    return

end function rate_oxygen_desorption_bridge_bridge


function gr_oxygen_desorption_bridge_cus_le0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_desorption_bridge_cus_le0000


    gr_oxygen_desorption_bridge_cus_le0000 = rate_oxygen_desorption_bridge_cus_le0000()
    return

end function gr_oxygen_desorption_bridge_cus_le0000

function rate_oxygen_desorption_bridge_cus_le0000()


    real(kind=rdouble) :: rate_oxygen_desorption_bridge_cus_le0000
    rate_oxygen_desorption_bridge_cus_le0000 = rates(oxygen_desorption_bridge_cus_le0000)
    return

end function rate_oxygen_desorption_bridge_cus_le0000


function gr_oxygen_desorption_bridge_cus_ri0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_desorption_bridge_cus_ri0000


    gr_oxygen_desorption_bridge_cus_ri0000 = rate_oxygen_desorption_bridge_cus_ri0000()
    return

end function gr_oxygen_desorption_bridge_cus_ri0000

function rate_oxygen_desorption_bridge_cus_ri0000()


    real(kind=rdouble) :: rate_oxygen_desorption_bridge_cus_ri0000
    rate_oxygen_desorption_bridge_cus_ri0000 = rates(oxygen_desorption_bridge_cus_ri0000)
    return

end function rate_oxygen_desorption_bridge_cus_ri0000


function gr_oxygen_desorption_cus_cus(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_desorption_cus_cus


    gr_oxygen_desorption_cus_cus = rate_oxygen_desorption_cus_cus()
    return

end function gr_oxygen_desorption_cus_cus

function rate_oxygen_desorption_cus_cus()


    real(kind=rdouble) :: rate_oxygen_desorption_cus_cus
    rate_oxygen_desorption_cus_cus = rates(oxygen_desorption_cus_cus)
    return

end function rate_oxygen_desorption_cus_cus


function gr_oxygen_diffusion_bridge_bridge_0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_diffusion_bridge_bridge_0000


    gr_oxygen_diffusion_bridge_bridge_0000 = rate_oxygen_diffusion_bridge_bridge_0000()
    return

end function gr_oxygen_diffusion_bridge_bridge_0000

function rate_oxygen_diffusion_bridge_bridge_0000()


    real(kind=rdouble) :: rate_oxygen_diffusion_bridge_bridge_0000
    rate_oxygen_diffusion_bridge_bridge_0000 = rates(oxygen_diffusion_bridge_bridge_0000)
    return

end function rate_oxygen_diffusion_bridge_bridge_0000


function gr_oxygen_diffusion_bridge_bridge_0001(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_diffusion_bridge_bridge_0001


    gr_oxygen_diffusion_bridge_bridge_0001 = rate_oxygen_diffusion_bridge_bridge_0001()
    return

end function gr_oxygen_diffusion_bridge_bridge_0001

function rate_oxygen_diffusion_bridge_bridge_0001()


    real(kind=rdouble) :: rate_oxygen_diffusion_bridge_bridge_0001
    rate_oxygen_diffusion_bridge_bridge_0001 = rates(oxygen_diffusion_bridge_bridge_0001)
    return

end function rate_oxygen_diffusion_bridge_bridge_0001


function gr_oxygen_diffusion_bridge_cus_lef0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_diffusion_bridge_cus_lef0000


    gr_oxygen_diffusion_bridge_cus_lef0000 = rate_oxygen_diffusion_bridge_cus_lef0000()
    return

end function gr_oxygen_diffusion_bridge_cus_lef0000

function rate_oxygen_diffusion_bridge_cus_lef0000()


    real(kind=rdouble) :: rate_oxygen_diffusion_bridge_cus_lef0000
    rate_oxygen_diffusion_bridge_cus_lef0000 = rates(oxygen_diffusion_bridge_cus_lef0000)
    return

end function rate_oxygen_diffusion_bridge_cus_lef0000


function gr_oxygen_diffusion_bridge_cus_rig0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_diffusion_bridge_cus_rig0000


    gr_oxygen_diffusion_bridge_cus_rig0000 = rate_oxygen_diffusion_bridge_cus_rig0000()
    return

end function gr_oxygen_diffusion_bridge_cus_rig0000

function rate_oxygen_diffusion_bridge_cus_rig0000()


    real(kind=rdouble) :: rate_oxygen_diffusion_bridge_cus_rig0000
    rate_oxygen_diffusion_bridge_cus_rig0000 = rates(oxygen_diffusion_bridge_cus_rig0000)
    return

end function rate_oxygen_diffusion_bridge_cus_rig0000


function gr_oxygen_diffusion_cus_bridge_lef0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_diffusion_cus_bridge_lef0000


    gr_oxygen_diffusion_cus_bridge_lef0000 = rate_oxygen_diffusion_cus_bridge_lef0000()
    return

end function gr_oxygen_diffusion_cus_bridge_lef0000

function rate_oxygen_diffusion_cus_bridge_lef0000()


    real(kind=rdouble) :: rate_oxygen_diffusion_cus_bridge_lef0000
    rate_oxygen_diffusion_cus_bridge_lef0000 = rates(oxygen_diffusion_cus_bridge_lef0000)
    return

end function rate_oxygen_diffusion_cus_bridge_lef0000


function gr_oxygen_diffusion_cus_bridge_rig0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_diffusion_cus_bridge_rig0000


    gr_oxygen_diffusion_cus_bridge_rig0000 = rate_oxygen_diffusion_cus_bridge_rig0000()
    return

end function gr_oxygen_diffusion_cus_bridge_rig0000

function rate_oxygen_diffusion_cus_bridge_rig0000()


    real(kind=rdouble) :: rate_oxygen_diffusion_cus_bridge_rig0000
    rate_oxygen_diffusion_cus_bridge_rig0000 = rates(oxygen_diffusion_cus_bridge_rig0000)
    return

end function rate_oxygen_diffusion_cus_bridge_rig0000


function gr_oxygen_diffusion_cus_cus_down(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_diffusion_cus_cus_down


    gr_oxygen_diffusion_cus_cus_down = rate_oxygen_diffusion_cus_cus_down()
    return

end function gr_oxygen_diffusion_cus_cus_down

function rate_oxygen_diffusion_cus_cus_down()


    real(kind=rdouble) :: rate_oxygen_diffusion_cus_cus_down
    rate_oxygen_diffusion_cus_cus_down = rates(oxygen_diffusion_cus_cus_down)
    return

end function rate_oxygen_diffusion_cus_cus_down


function gr_oxygen_diffusion_cus_cus_up(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_oxygen_diffusion_cus_cus_up


    gr_oxygen_diffusion_cus_cus_up = rate_oxygen_diffusion_cus_cus_up()
    return

end function gr_oxygen_diffusion_cus_cus_up

function rate_oxygen_diffusion_cus_cus_up()


    real(kind=rdouble) :: rate_oxygen_diffusion_cus_cus_up
    rate_oxygen_diffusion_cus_cus_up = rates(oxygen_diffusion_cus_cus_up)
    return

end function rate_oxygen_diffusion_cus_cus_up


function gr_reaction_oxygen_bridge_co_bridg0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_reaction_oxygen_bridge_co_bridg0000


    gr_reaction_oxygen_bridge_co_bridg0000 = rate_reaction_oxygen_bridge_co_bridg0000()
    return

end function gr_reaction_oxygen_bridge_co_bridg0000

function rate_reaction_oxygen_bridge_co_bridg0000()


    real(kind=rdouble) :: rate_reaction_oxygen_bridge_co_bridg0000
    rate_reaction_oxygen_bridge_co_bridg0000 = rates(reaction_oxygen_bridge_co_bridg0000)
    return

end function rate_reaction_oxygen_bridge_co_bridg0000


function gr_reaction_oxygen_bridge_co_bridg0001(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_reaction_oxygen_bridge_co_bridg0001


    gr_reaction_oxygen_bridge_co_bridg0001 = rate_reaction_oxygen_bridge_co_bridg0001()
    return

end function gr_reaction_oxygen_bridge_co_bridg0001

function rate_reaction_oxygen_bridge_co_bridg0001()


    real(kind=rdouble) :: rate_reaction_oxygen_bridge_co_bridg0001
    rate_reaction_oxygen_bridge_co_bridg0001 = rates(reaction_oxygen_bridge_co_bridg0001)
    return

end function rate_reaction_oxygen_bridge_co_bridg0001


function gr_reaction_oxygen_bridge_co_cus_l0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_reaction_oxygen_bridge_co_cus_l0000


    gr_reaction_oxygen_bridge_co_cus_l0000 = rate_reaction_oxygen_bridge_co_cus_l0000()
    return

end function gr_reaction_oxygen_bridge_co_cus_l0000

function rate_reaction_oxygen_bridge_co_cus_l0000()


    real(kind=rdouble) :: rate_reaction_oxygen_bridge_co_cus_l0000
    rate_reaction_oxygen_bridge_co_cus_l0000 = rates(reaction_oxygen_bridge_co_cus_l0000)
    return

end function rate_reaction_oxygen_bridge_co_cus_l0000


function gr_reaction_oxygen_bridge_co_cus_r0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_reaction_oxygen_bridge_co_cus_r0000


    gr_reaction_oxygen_bridge_co_cus_r0000 = rate_reaction_oxygen_bridge_co_cus_r0000()
    return

end function gr_reaction_oxygen_bridge_co_cus_r0000

function rate_reaction_oxygen_bridge_co_cus_r0000()


    real(kind=rdouble) :: rate_reaction_oxygen_bridge_co_cus_r0000
    rate_reaction_oxygen_bridge_co_cus_r0000 = rates(reaction_oxygen_bridge_co_cus_r0000)
    return

end function rate_reaction_oxygen_bridge_co_cus_r0000


function gr_reaction_oxygen_cus_co_bridge_l0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_reaction_oxygen_cus_co_bridge_l0000


    gr_reaction_oxygen_cus_co_bridge_l0000 = rate_reaction_oxygen_cus_co_bridge_l0000()
    return

end function gr_reaction_oxygen_cus_co_bridge_l0000

function rate_reaction_oxygen_cus_co_bridge_l0000()


    real(kind=rdouble) :: rate_reaction_oxygen_cus_co_bridge_l0000
    rate_reaction_oxygen_cus_co_bridge_l0000 = rates(reaction_oxygen_cus_co_bridge_l0000)
    return

end function rate_reaction_oxygen_cus_co_bridge_l0000


function gr_reaction_oxygen_cus_co_bridge_r0000(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_reaction_oxygen_cus_co_bridge_r0000


    gr_reaction_oxygen_cus_co_bridge_r0000 = rate_reaction_oxygen_cus_co_bridge_r0000()
    return

end function gr_reaction_oxygen_cus_co_bridge_r0000

function rate_reaction_oxygen_cus_co_bridge_r0000()


    real(kind=rdouble) :: rate_reaction_oxygen_cus_co_bridge_r0000
    rate_reaction_oxygen_cus_co_bridge_r0000 = rates(reaction_oxygen_cus_co_bridge_r0000)
    return

end function rate_reaction_oxygen_cus_co_bridge_r0000


function gr_reaction_oxygen_cus_co_cus_down(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_reaction_oxygen_cus_co_cus_down


    gr_reaction_oxygen_cus_co_cus_down = rate_reaction_oxygen_cus_co_cus_down()
    return

end function gr_reaction_oxygen_cus_co_cus_down

function rate_reaction_oxygen_cus_co_cus_down()


    real(kind=rdouble) :: rate_reaction_oxygen_cus_co_cus_down
    rate_reaction_oxygen_cus_co_cus_down = rates(reaction_oxygen_cus_co_cus_down)
    return

end function rate_reaction_oxygen_cus_co_cus_down


function gr_reaction_oxygen_cus_co_cus_up(cell)
    integer(kind=iint), dimension(4), intent(in) :: cell
    real(kind=rdouble) :: gr_reaction_oxygen_cus_co_cus_up


    gr_reaction_oxygen_cus_co_cus_up = rate_reaction_oxygen_cus_co_cus_up()
    return

end function gr_reaction_oxygen_cus_co_cus_up

function rate_reaction_oxygen_cus_co_cus_up()


    real(kind=rdouble) :: rate_reaction_oxygen_cus_co_cus_up
    rate_reaction_oxygen_cus_co_cus_up = rates(reaction_oxygen_cus_co_cus_up)
    return

end function rate_reaction_oxygen_cus_co_cus_up


end module proclist_pars
